In [143]:
# Importing modules
import pandas as pd
import numpy as np

## Datasets

Box Office Mojo:
- bom.movie_gross.csv.gz

IMDB (more infor info [here](https://www.imdb.com/interfaces/)):
- imdb.name.basics.csv.gz
- imdb.title.akas.csv.gz
- imdb.title.basics.csv.gz
- imdb.title.crew.csv.gz
- imdb.title.principals.csv.gz
- imdb.title.ratings.csv.gz

Rotten Tomatoes:
- rt.movie_info.tsv.gz
- rt.reviews.tsv.gz

TheMovieDB:
- tmdb.movies.csv.gz

The Numbers:
- tn.movie_budgets.csv.gz

In [144]:
bom_movie_gross_df = pd.read_csv('zippedData/bom.movie_gross.csv.gz')
bom_movie_gross_df

,title,studio,domestic_gross,foreign_gross,year
0,Toy Story 3,BV,415000000.0,652000000,2010
1,Alice in Wonderland (2010),BV,334200000.0,691300000,2010
2,Harry Potter and the Deathly Hallows Part 1,WB,296000000.0,664300000,2010
3,Inception,WB,292600000.0,535700000,2010
4,Shrek Forever After,P/DW,238700000.0,513900000,2010
...,...,...,...,...,...
3382,The Quake,Magn.,6200.0,NaN,2018
3383,Edward II (2018 re-release),FM,4800.0,NaN,2018
3384,El Pacto,Sony,2500.0,NaN,2018
3385,The Swan,Synergetic,2400.0,NaN,2018
3386,An Actor Prepares,Grav.,1700.0,NaN,2018

In [145]:
imdb_name_basics_df = pd.read_csv('zippedData/imdb.name.basics.csv.gz')
imdb_name_basics_df['primary_profession'] = imdb_name_basics_df['primary_profession'].str.strip(',')
imdb_name_basics_df

,nconst,primary_name,birth_year,death_year,primary_profession,known_for_titles
0,nm0061671,Mary Ellen Bauder,NaN,NaN,"miscellaneous,production_manager,producer","tt0837562,tt2398241,tt0844471,tt0118553"
1,nm0061865,Joseph Bauer,NaN,NaN,"composer,music_department,sound_department","tt0896534,tt6791238,tt0287072,tt1682940"
2,nm0062070,Bruce Baum,NaN,NaN,"miscellaneous,actor,writer","tt1470654,tt0363631,tt0104030,tt0102898"
3,nm0062195,Axel Baumann,NaN,NaN,"camera_department,cinematographer,art_department","tt0114371,tt2004304,tt1618448,tt1224387"
4,nm0062798,Pete Baxter,NaN,NaN,"production_designer,art_department,set_decorator","tt0452644,tt0452692,tt3458030,tt2178256"
...,...,...,...,...,...,...
606643,nm9990381,Susan Grobes,NaN,NaN,actress,NaN
606644,nm9990690,Joo Yeon So,NaN,NaN,actress,"tt9090932,tt8737130"
606645,nm9991320,Madeline Smith,NaN,NaN,actress,"tt8734436,tt9615610"
606646,nm9991786,Michelle Modigliani,NaN,NaN,producer,NaN
606647,nm9993380,Pegasus Envoyé,NaN,NaN,"director,actor,writer",tt8743182

In [146]:
imdb_title_akas_df = pd.read_csv('zippedData/imdb.title.akas.csv.gz')
imdb_title_akas_df

,title_id,ordering,title,region,language,types,attributes,is_original_title
0,tt0369610,10,Джурасик свят,BG,bg,NaN,NaN,0.0
1,tt0369610,11,Jurashikku warudo,JP,NaN,imdbDisplay,NaN,0.0
2,tt0369610,12,Jurassic World: O Mundo dos Dinossauros,BR,NaN,imdbDisplay,NaN,0.0
3,tt0369610,13,O Mundo dos Dinossauros,BR,NaN,NaN,short title,0.0
4,tt0369610,14,Jurassic World,FR,NaN,imdbDisplay,NaN,0.0
...,...,...,...,...,...,...,...,...
331698,tt9827784,2,Sayonara kuchibiru,NaN,NaN,original,NaN,1.0
331699,tt9827784,3,Farewell Song,XWW,en,imdbDisplay,NaN,0.0
331700,tt9880178,1,La atención,NaN,NaN,original,NaN,1.0
331701,tt9880178,2,La atención,ES,NaN,NaN,NaN,0.0
331702,tt9880178,3,The Attention,XWW,en,imdbDisplay,NaN,0.0

In [147]:
imdb_title_basics_df = pd.read_csv('zippedData/imdb.title.basics.csv.gz')
imdb_title_basics_df.rename(columns={'primary_title': 'movie'}, inplace=True)
imdb_title_basics_df

,tconst,movie,original_title,start_year,runtime_minutes,genres
0,tt0063540,Sunghursh,Sunghursh,2013,175.0,"Action,Crime,Drama"
1,tt0066787,One Day Before the Rainy Season,Ashad Ka Ek Din,2019,114.0,"Biography,Drama"
2,tt0069049,The Other Side of the Wind,The Other Side of the Wind,2018,122.0,Drama
3,tt0069204,Sabse Bada Sukh,Sabse Bada Sukh,2018,NaN,"Comedy,Drama"
4,tt0100275,The Wandering Soap Opera,La Telenovela Errante,2017,80.0,"Comedy,Drama,Fantasy"
...,...,...,...,...,...,...
146139,tt9916538,Kuambil Lagi Hatiku,Kuambil Lagi Hatiku,2019,123.0,Drama
146140,tt9916622,Rodolpho Teóphilo - O Legado de um Pioneiro,Rodolpho Teóphilo - O Legado de um Pioneiro,2015,NaN,Documentary
146141,tt9916706,Dankyavar Danka,Dankyavar Danka,2013,NaN,Comedy
146142,tt9916730,6 Gunn,6 Gunn,2017,116.0,NaN
146143,tt9916754,Chico Albuquerque - Revelações,Chico Albuquerque - Revelações,2013,NaN,Documentary

In [149]:
imdb_title_crew_df = pd.read_csv('zippedData/imdb.title.crew.csv.gz')
imdb_title_crew_df.dropna(inplace=True)
imdb_title_crew_df

           tconst                      directors                writers
0       tt0285252                      nm0899854              nm0899854
2       tt0462036                      nm1940585              nm1940585
3       tt0835418                      nm0151540    nm0310087,nm0841532
4       tt0878654  nm0089502,nm2291498,nm2292011              nm0284943
6       tt0996958                      nm2286991    nm2286991,nm2651190
...           ...                            ...                    ...
146137  tt8998302                     nm10121510             nm10121510
146138  tt8999892                     nm10122247  nm10122247,nm10122246
146139  tt8999974                     nm10122357             nm10122357
146140  tt9001390                      nm6711477              nm6711477
146142  tt9004986                      nm4993825              nm4993825

[109008 rows x 3 columns]

In [150]:
imdb_title_principals_df = pd.read_csv('zippedData/imdb.title.principals.csv.gz')
imdb_title_principals_df

,tconst,ordering,nconst,category,job,characters
0,tt0111414,1,nm0246005,actor,NaN,"[""The Man""]"
1,tt0111414,2,nm0398271,director,NaN,NaN
2,tt0111414,3,nm3739909,producer,producer,NaN
3,tt0323808,10,nm0059247,editor,NaN,NaN
4,tt0323808,1,nm3579312,actress,NaN,"[""Beth Boothby""]"
...,...,...,...,...,...,...
1028181,tt9692684,1,nm0186469,actor,NaN,"[""Ebenezer Scrooge""]"
1028182,tt9692684,2,nm4929530,self,NaN,"[""Herself"",""Regan""]"
1028183,tt9692684,3,nm10441594,director,NaN,NaN
1028184,tt9692684,4,nm6009913,writer,writer,NaN
1028185,tt9692684,5,nm10441595,producer,producer,NaN

In [151]:
imdb_title_ratings_df = pd.read_csv('zippedData/imdb.title.ratings.csv.gz')
imdb_title_ratings_df

           tconst  averagerating  numvotes
0      tt10356526            8.3        31
1      tt10384606            8.9       559
2       tt1042974            6.4        20
3       tt1043726            4.2     50352
4       tt1060240            6.5        21
...           ...            ...       ...
73851   tt9805820            8.1        25
73852   tt9844256            7.5        24
73853   tt9851050            4.7        14
73854   tt9886934            7.0         5
73855   tt9894098            6.3       128

[73856 rows x 3 columns]

In [152]:
rt_movie_info_df = pd.read_csv('zippedData/rt.movie_info.tsv.gz', delimiter='\t')
rt_movie_info_df

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
0,1,"This gritty, fast-paced, and innovative police...",R,Action and Adventure|Classics|Drama,William Friedkin,Ernest Tidyman,"Oct 9, 1971","Sep 25, 2001",NaN,NaN,104 minutes,NaN
1,3,"New York City, not-too-distant-future: Eric Pa...",R,Drama|Science Fiction and Fantasy,David Cronenberg,David Cronenberg|Don DeLillo,"Aug 17, 2012","Jan 1, 2013",$,"600,000",108 minutes,Entertainment One
2,5,Illeana Douglas delivers a superb performance ...,R,Drama|Musical and Performing Arts,Allison Anders,Allison Anders,"Sep 13, 1996","Apr 18, 2000",NaN,NaN,116 minutes,NaN
3,6,Michael Douglas runs afoul of a treacherous su...,R,Drama|Mystery and Suspense,Barry Levinson,Paul Attanasio|Michael Crichton,"Dec 9, 1994","Aug 27, 1997",NaN,NaN,128 minutes,NaN
4,7,NaN,NR,Drama|Romance,Rodney Bennett,Giles Cooper,NaN,NaN,NaN,NaN,200 minutes,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1555,1996,Forget terrorists or hijackers -- there's a ha...,R,Action and Adventure|Horror|Mystery and Suspense,NaN,NaN,"Aug 18, 2006","Jan 2, 2007",$,"33,886,034",106 minutes,New Line Cinema
1556,1997,The popular Saturday Night Live sketch was exp...,PG,Comedy|Science Fiction and Fantasy,Steve Barron,Terry Turner|Tom Davis|Dan Aykroyd|Bonnie Turner,"Jul 23, 1993","Apr 17, 2001",NaN,NaN,88 minutes,Paramount Vantage
1557,1998,"Based on a novel by Richard Powell, when the l...",G,Classics|Comedy|Drama|Musical and Performing Arts,Gordon Douglas,NaN,"Jan 1, 1962","May 11, 2004",NaN,NaN,111 minutes,NaN
1558,1999,The Sandlot is a coming-of-age story about a g...,PG,Comedy|Drama|Kids and Family|Sports and Fitness,David Mickey Evans,David Mickey Evans|Robert Gunter,"Apr 1, 1993","Jan 29, 2002",NaN,NaN,101 minutes,NaN
1559,2000,"Suspended from the force, Paris cop Hubert is ...",R,Action and Adventure|Art House and Internation...,NaN,Luc Besson,"Sep 27, 2001","Feb 11, 2003",NaN,NaN,94 minutes,Columbia Pictures

In [153]:
rt_reviews_df = pd.read_csv('zippedData/rt.reviews.tsv.gz', delimiter='\t', encoding='latin-1')
rt_reviews_df

,id,review,rating,fresh,critic,top_critic,publisher,date
0,3,A distinctly gallows take on contemporary fina...,3/5,fresh,PJ Nabarro,0,Patrick Nabarro,"November 10, 2018"
1,3,It's an allegory in search of a meaning that n...,NaN,rotten,Annalee Newitz,0,io9.com,"May 23, 2018"
2,3,... life lived in a bubble in financial dealin...,NaN,fresh,Sean Axmaker,0,Stream on Demand,"January 4, 2018"
3,3,Continuing along a line introduced in last yea...,NaN,fresh,Daniel Kasman,0,MUBI,"November 16, 2017"
4,3,... a perverse twist on neorealism...,NaN,fresh,NaN,0,Cinema Scope,"October 12, 2017"
...,...,...,...,...,...,...,...,...
54427,2000,The real charm of this trifle is the deadpan c...,NaN,fresh,Laura Sinagra,1,Village Voice,"September 24, 2002"
54428,2000,NaN,1/5,rotten,Michael Szymanski,0,Zap2it.com,"September 21, 2005"
54429,2000,NaN,2/5,rotten,Emanuel Levy,0,EmanuelLevy.Com,"July 17, 2005"
54430,2000,NaN,2.5/5,rotten,Christopher Null,0,Filmcritic.com,"September 7, 2003"
54431,2000,NaN,3/5,fresh,Nicolas Lacroix,0,Showbizz.net,"November 12, 2002"

In [154]:
tmdb_movies_df = pd.read_csv('zippedData/tmdb.movies.csv.gz')
tmdb_movies_df

,Unnamed: 0,genre_ids,id,original_language,original_title,popularity,release_date,title,vote_average,vote_count
0,0,"[12, 14, 10751]",12444,en,Harry Potter and the Deathly Hallows: Part 1,33.533,2010-11-19,Harry Potter and the Deathly Hallows: Part 1,7.7,10788
1,1,"[14, 12, 16, 10751]",10191,en,How to Train Your Dragon,28.734,2010-03-26,How to Train Your Dragon,7.7,7610
2,2,"[12, 28, 878]",10138,en,Iron Man 2,28.515,2010-05-07,Iron Man 2,6.8,12368
3,3,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174
4,4,"[28, 878, 12]",27205,en,Inception,27.920,2010-07-16,Inception,8.3,22186
...,...,...,...,...,...,...,...,...,...,...
26512,26512,"[27, 18]",488143,en,Laboratory Conditions,0.600,2018-10-13,Laboratory Conditions,0.0,1
26513,26513,"[18, 53]",485975,en,_EXHIBIT_84xxx_,0.600,2018-05-01,_EXHIBIT_84xxx_,0.0,1
26514,26514,"[14, 28, 12]",381231,en,The Last One,0.600,2018-10-01,The Last One,0.0,1
26515,26515,"[10751, 12, 28]",366854,en,Trailer Made,0.600,2018-06-22,Trailer Made,0.0,1
26516,26516,"[53, 27]",309885,en,The Church,0.600,2018-10-05,The Church,0.0,1

In [156]:
tn_movie_budgets_df = pd.read_csv('zippedData/tn.movie_budgets.csv.gz')
tn_movie_budgets_df

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
0,1,"Dec 18, 2009",Avatar,"$425,000,000","$760,507,625","$2,776,345,279"
1,2,"May 20, 2011",Pirates of the Caribbean: On Stranger Tides,"$410,600,000","$241,063,875","$1,045,663,875"
2,3,"Jun 7, 2019",Dark Phoenix,"$350,000,000","$42,762,350","$149,762,350"
3,4,"May 1, 2015",Avengers: Age of Ultron,"$330,600,000","$459,005,868","$1,403,013,963"
4,5,"Dec 15, 2017",Star Wars Ep. VIII: The Last Jedi,"$317,000,000","$620,181,382","$1,316,721,747"
...,...,...,...,...,...,...
5777,78,"Dec 31, 2018",Red 11,"$7,000",$0,$0
5778,79,"Apr 2, 1999",Following,"$6,000","$48,482","$240,495"
5779,80,"Jul 13, 2005",Return to the Land of Wonders,"$5,000","$1,338","$1,338"
5780,81,"Sep 29, 2015",A Plague So Pleasant,"$1,400",$0,$0
5781,82,"Aug 5, 2005",My Date With Drew,"$1,100","$181,041","$181,041"

In [157]:
imdb_title_basics_df

,tconst,movie,original_title,start_year,runtime_minutes,genres
0,tt0063540,Sunghursh,Sunghursh,2013,175.0,"Action,Crime,Drama"
1,tt0066787,One Day Before the Rainy Season,Ashad Ka Ek Din,2019,114.0,"Biography,Drama"
2,tt0069049,The Other Side of the Wind,The Other Side of the Wind,2018,122.0,Drama
3,tt0069204,Sabse Bada Sukh,Sabse Bada Sukh,2018,NaN,"Comedy,Drama"
4,tt0100275,The Wandering Soap Opera,La Telenovela Errante,2017,80.0,"Comedy,Drama,Fantasy"
...,...,...,...,...,...,...
146139,tt9916538,Kuambil Lagi Hatiku,Kuambil Lagi Hatiku,2019,123.0,Drama
146140,tt9916622,Rodolpho Teóphilo - O Legado de um Pioneiro,Rodolpho Teóphilo - O Legado de um Pioneiro,2015,NaN,Documentary
146141,tt9916706,Dankyavar Danka,Dankyavar Danka,2013,NaN,Comedy
146142,tt9916730,6 Gunn,6 Gunn,2017,116.0,NaN
146143,tt9916754,Chico Albuquerque - Revelações,Chico Albuquerque - Revelações,2013,NaN,Documentary

In [158]:
 imdb_title_basics_df['movie'].isin(tn_movie_budgets_df['movie']).value_counts()

False    142538
True       3606
Name: movie, dtype: int64

In [159]:
tn_movie_budgets_df = pd.read_csv('zippedData/tn.movie_budgets.csv.gz')
tn_movie_budgets_df['start_year'] = tn_movie_budgets_df['release_date'].map(lambda x: int(x[-4:]))    
tn_movie_budgets_df

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross,start_year
0,1,"Dec 18, 2009",Avatar,"$425,000,000","$760,507,625","$2,776,345,279",2009
1,2,"May 20, 2011",Pirates of the Caribbean: On Stranger Tides,"$410,600,000","$241,063,875","$1,045,663,875",2011
2,3,"Jun 7, 2019",Dark Phoenix,"$350,000,000","$42,762,350","$149,762,350",2019
3,4,"May 1, 2015",Avengers: Age of Ultron,"$330,600,000","$459,005,868","$1,403,013,963",2015
4,5,"Dec 15, 2017",Star Wars Ep. VIII: The Last Jedi,"$317,000,000","$620,181,382","$1,316,721,747",2017
...,...,...,...,...,...,...,...
5777,78,"Dec 31, 2018",Red 11,"$7,000",$0,$0,2018
5778,79,"Apr 2, 1999",Following,"$6,000","$48,482","$240,495",1999
5779,80,"Jul 13, 2005",Return to the Land of Wonders,"$5,000","$1,338","$1,338",2005
5780,81,"Sep 29, 2015",A Plague So Pleasant,"$1,400",$0,$0,2015
5781,82,"Aug 5, 2005",My Date With Drew,"$1,100","$181,041","$181,041",2005

In [160]:
imdb_title_basics_df

,tconst,movie,original_title,start_year,runtime_minutes,genres
0,tt0063540,Sunghursh,Sunghursh,2013,175.0,"Action,Crime,Drama"
1,tt0066787,One Day Before the Rainy Season,Ashad Ka Ek Din,2019,114.0,"Biography,Drama"
2,tt0069049,The Other Side of the Wind,The Other Side of the Wind,2018,122.0,Drama
3,tt0069204,Sabse Bada Sukh,Sabse Bada Sukh,2018,NaN,"Comedy,Drama"
4,tt0100275,The Wandering Soap Opera,La Telenovela Errante,2017,80.0,"Comedy,Drama,Fantasy"
...,...,...,...,...,...,...
146139,tt9916538,Kuambil Lagi Hatiku,Kuambil Lagi Hatiku,2019,123.0,Drama
146140,tt9916622,Rodolpho Teóphilo - O Legado de um Pioneiro,Rodolpho Teóphilo - O Legado de um Pioneiro,2015,NaN,Documentary
146141,tt9916706,Dankyavar Danka,Dankyavar Danka,2013,NaN,Comedy
146142,tt9916730,6 Gunn,6 Gunn,2017,116.0,NaN
146143,tt9916754,Chico Albuquerque - Revelações,Chico Albuquerque - Revelações,2013,NaN,Documentary

In [161]:
#renaming it to work on
money_metrics_df = tn_movie_budgets_df

#funtion for cleaning
def clean_a_money_column(df, series_title):
    df[series_title] = df[series_title].str.replace('$','')
    df[series_title] = df[series_title].str.replace(',','')
    df[series_title] = pd.to_numeric(df[series_title])
    return df

#cleaning
money_metrics_df = clean_a_money_column(money_metrics_df,'worldwide_gross')
money_metrics_df = clean_a_money_column(money_metrics_df,'domestic_gross')
money_metrics_df = clean_a_money_column(money_metrics_df,'production_budget')

#adding profit margin and ROI columns
money_metrics_df['Profit Margin']= (money_metrics_df['worldwide_gross']-money_metrics_df['production_budget'])/money_metrics_df['worldwide_gross']
money_metrics_df['ROI'] = (money_metrics_df['worldwide_gross']/money_metrics_df['production_budget'])

#creating year and month columns
money_metrics_df['Year'] = money_metrics_df['release_date']


#Vu's magic lambda, plus to numeric on the year 
money_metrics_df['Year'] = pd.to_numeric(money_metrics_df['release_date'].map(lambda x: int(x[-4:])))
money_metrics_df['Month'] = money_metrics_df['release_date'].map(lambda x: x[:3])

In [162]:
money_metrics_df

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross,start_year,Profit Margin,ROI,Year,Month
0,1,"Dec 18, 2009",Avatar,425000000,760507625,2776345279,2009,0.846921,6.532577,2009,Dec
1,2,"May 20, 2011",Pirates of the Caribbean: On Stranger Tides,410600000,241063875,1045663875,2011,0.607331,2.546673,2011,May
2,3,"Jun 7, 2019",Dark Phoenix,350000000,42762350,149762350,2019,-1.337036,0.427892,2019,Jun
3,4,"May 1, 2015",Avengers: Age of Ultron,330600000,459005868,1403013963,2015,0.764364,4.243841,2015,May
4,5,"Dec 15, 2017",Star Wars Ep. VIII: The Last Jedi,317000000,620181382,1316721747,2017,0.759251,4.153696,2017,Dec
...,...,...,...,...,...,...,...,...,...,...,...
5777,78,"Dec 31, 2018",Red 11,7000,0,0,2018,-inf,0.000000,2018,Dec
5778,79,"Apr 2, 1999",Following,6000,48482,240495,1999,0.975051,40.082500,1999,Apr
5779,80,"Jul 13, 2005",Return to the Land of Wonders,5000,1338,1338,2005,-2.736921,0.267600,2005,Jul
5780,81,"Sep 29, 2015",A Plague So Pleasant,1400,0,0,2015,-inf,0.000000,2015,Sep
5781,82,"Aug 5, 2005",My Date With Drew,1100,181041,181041,2005,0.993924,164.582727,2005,Aug

In [163]:
temp = imdb_title_basics_df.merge(money_metrics_df, how='inner', on='movie')

In [164]:
temp

,tconst,movie,original_title,start_year_x,runtime_minutes,genres,id,release_date,production_budget,domestic_gross,worldwide_gross,start_year_y,Profit Margin,ROI,Year,Month
0,tt0249516,Foodfight!,Foodfight!,2012,91.0,"Action,Animation,Comedy",26,"Dec 31, 2012",45000000,0,73706,2012,-609.533742,0.001638,2012,Dec
1,tt0293429,Mortal Kombat,Mortal Kombat,2021,NaN,"Action,Adventure,Fantasy",10,"Aug 18, 1995",20000000,70433227,122133227,1995,0.836244,6.106661,1995,Aug
2,tt0326592,The Overnight,The Overnight,2010,88.0,NaN,21,"Jun 19, 2015",200000,1109808,1165996,2015,0.828473,5.829980,2015,Jun
3,tt3844362,The Overnight,The Overnight,2015,79.0,"Comedy,Mystery",21,"Jun 19, 2015",200000,1109808,1165996,2015,0.828473,5.829980,2015,Jun
4,tt0337692,On the Road,On the Road,2012,124.0,"Adventure,Drama,Romance",17,"Mar 22, 2013",25000000,720828,9313302,2013,-1.684333,0.372532,2013,Mar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3810,tt9678962,Fuel,Fuel,2018,NaN,"Documentary,Sport",35,"Nov 14, 2008",2500000,174255,174255,2008,-13.346791,0.069702,2008,Nov
3811,tt9729206,Diner,Diner,2019,NaN,Crime,11,"Apr 2, 1982",5000000,12592907,12592907,1982,0.602951,2.518581,1982,Apr
3812,tt9805168,Traitor,Traitor,2015,110.0,"Action,Drama,Romance",25,"Aug 27, 2008",22000000,23530831,27882226,2008,0.210967,1.267374,2008,Aug
3813,tt9844102,Ray,Ray,2018,111.0,Crime,8,"Oct 29, 2004",40000000,75305995,124823094,2004,0.679546,3.120577,2004,Oct
3814,tt9893078,Sublime,Sublime,2019,NaN,Documentary,30,"Mar 13, 2007",1800000,0,0,2007,-inf,0.000000,2007,Mar

In [165]:
temp.drop(['runtime_minutes'], axis=1, inplace=True)

In [166]:
temp.dropna(subset=['Profit Margin', 'ROI'], inplace=True)

In [167]:
temp = temp.merge(imdb_title_ratings_df, how='left', on='tconst')

In [168]:
temp

,tconst,movie,original_title,start_year_x,genres,id,release_date,production_budget,domestic_gross,worldwide_gross,start_year_y,Profit Margin,ROI,Year,Month,averagerating,numvotes
0,tt0249516,Foodfight!,Foodfight!,2012,"Action,Animation,Comedy",26,"Dec 31, 2012",45000000,0,73706,2012,-609.533742,0.001638,2012,Dec,1.9,8248.0
1,tt0293429,Mortal Kombat,Mortal Kombat,2021,"Action,Adventure,Fantasy",10,"Aug 18, 1995",20000000,70433227,122133227,1995,0.836244,6.106661,1995,Aug,NaN,NaN
2,tt0326592,The Overnight,The Overnight,2010,NaN,21,"Jun 19, 2015",200000,1109808,1165996,2015,0.828473,5.829980,2015,Jun,7.5,24.0
3,tt3844362,The Overnight,The Overnight,2015,"Comedy,Mystery",21,"Jun 19, 2015",200000,1109808,1165996,2015,0.828473,5.829980,2015,Jun,6.1,14828.0
4,tt0337692,On the Road,On the Road,2012,"Adventure,Drama,Romance",17,"Mar 22, 2013",25000000,720828,9313302,2013,-1.684333,0.372532,2013,Mar,6.1,37886.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3810,tt9678962,Fuel,Fuel,2018,"Documentary,Sport",35,"Nov 14, 2008",2500000,174255,174255,2008,-13.346791,0.069702,2008,Nov,NaN,NaN
3811,tt9729206,Diner,Diner,2019,Crime,11,"Apr 2, 1982",5000000,12592907,12592907,1982,0.602951,2.518581,1982,Apr,NaN,NaN
3812,tt9805168,Traitor,Traitor,2015,"Action,Drama,Romance",25,"Aug 27, 2008",22000000,23530831,27882226,2008,0.210967,1.267374,2008,Aug,NaN,NaN
3813,tt9844102,Ray,Ray,2018,Crime,8,"Oct 29, 2004",40000000,75305995,124823094,2004,0.679546,3.120577,2004,Oct,NaN,NaN
3814,tt9893078,Sublime,Sublime,2019,Documentary,30,"Mar 13, 2007",1800000,0,0,2007,-inf,0.000000,2007,Mar,NaN,NaN

In [169]:
temp.drop(['genres'], axis=1,inplace=True)

In [170]:
temp

,tconst,movie,original_title,start_year_x,id,release_date,production_budget,domestic_gross,worldwide_gross,start_year_y,Profit Margin,ROI,Year,Month,averagerating,numvotes
0,tt0249516,Foodfight!,Foodfight!,2012,26,"Dec 31, 2012",45000000,0,73706,2012,-609.533742,0.001638,2012,Dec,1.9,8248.0
1,tt0293429,Mortal Kombat,Mortal Kombat,2021,10,"Aug 18, 1995",20000000,70433227,122133227,1995,0.836244,6.106661,1995,Aug,NaN,NaN
2,tt0326592,The Overnight,The Overnight,2010,21,"Jun 19, 2015",200000,1109808,1165996,2015,0.828473,5.829980,2015,Jun,7.5,24.0
3,tt3844362,The Overnight,The Overnight,2015,21,"Jun 19, 2015",200000,1109808,1165996,2015,0.828473,5.829980,2015,Jun,6.1,14828.0
4,tt0337692,On the Road,On the Road,2012,17,"Mar 22, 2013",25000000,720828,9313302,2013,-1.684333,0.372532,2013,Mar,6.1,37886.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3810,tt9678962,Fuel,Fuel,2018,35,"Nov 14, 2008",2500000,174255,174255,2008,-13.346791,0.069702,2008,Nov,NaN,NaN
3811,tt9729206,Diner,Diner,2019,11,"Apr 2, 1982",5000000,12592907,12592907,1982,0.602951,2.518581,1982,Apr,NaN,NaN
3812,tt9805168,Traitor,Traitor,2015,25,"Aug 27, 2008",22000000,23530831,27882226,2008,0.210967,1.267374,2008,Aug,NaN,NaN
3813,tt9844102,Ray,Ray,2018,8,"Oct 29, 2004",40000000,75305995,124823094,2004,0.679546,3.120577,2004,Oct,NaN,NaN
3814,tt9893078,Sublime,Sublime,2019,30,"Mar 13, 2007",1800000,0,0,2007,-inf,0.000000,2007,Mar,NaN,NaN

In [174]:
temp = temp.merge(imdb_title_principals_df, how='inner', on='tconst')

In [175]:
temp.drop(['original_title', 'id', 'characters'])

,tconst,movie,original_title,start_year_x,id,release_date,production_budget,domestic_gross,worldwide_gross,start_year_y,...,ROI,Year,Month,averagerating,numvotes,ordering,nconst,category,job,characters
0,tt0249516,Foodfight!,Foodfight!,2012,26,"Dec 31, 2012",45000000,0,73706,2012,...,0.001638,2012,Dec,1.9,8248.0,10,nm0257258,producer,producer,NaN
1,tt0249516,Foodfight!,Foodfight!,2012,26,"Dec 31, 2012",45000000,0,73706,2012,...,0.001638,2012,Dec,1.9,8248.0,1,nm0240381,actress,NaN,"[""Sunshine Goodness""]"
2,tt0249516,Foodfight!,Foodfight!,2012,26,"Dec 31, 2012",45000000,0,73706,2012,...,0.001638,2012,Dec,1.9,8248.0,2,nm0240380,actress,NaN,"[""Sweetcakes""]"
3,tt0249516,Foodfight!,Foodfight!,2012,26,"Dec 31, 2012",45000000,0,73706,2012,...,0.001638,2012,Dec,1.9,8248.0,3,nm0000221,actor,NaN,"[""Dex Dogtective""]"
4,tt0249516,Foodfight!,Foodfight!,2012,26,"Dec 31, 2012",45000000,0,73706,2012,...,0.001638,2012,Dec,1.9,8248.0,4,nm0519456,actress,NaN,"[""Lady X""]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32403,tt9893078,Sublime,Sublime,2019,30,"Mar 13, 2007",1800000,0,0,2007,...,0.000000,2007,Mar,NaN,NaN,4,nm1276349,producer,producer,NaN
32404,tt9893078,Sublime,Sublime,2019,30,"Mar 13, 2007",1800000,0,0,2007,...,0.000000,2007,Mar,NaN,NaN,5,nm0434940,composer,NaN,NaN
32405,tt9893078,Sublime,Sublime,2019,30,"Mar 13, 2007",1800000,0,0,2007,...,0.000000,2007,Mar,NaN,NaN,6,nm0443706,cinematographer,director of photography,NaN
32406,tt9893078,Sublime,Sublime,2019,30,"Mar 13, 2007",1800000,0,0,2007,...,0.000000,2007,Mar,NaN,NaN,7,nm0002237,editor,NaN,NaN
32407,tt9893078,Sublime,Sublime,2019,30,"Mar 13, 2007",1800000,0,0,2007,...,0.000000,2007,Mar,NaN,NaN,8,nm0829466,editor,NaN,NaN

In [61]:
writer_director_df = imdb_name_basics_df[imdb_name_basics_df['primary_profession'].str.contains( 'writer|director', na=False)]
writer_director_dict = pd.Series(writer_director_df.primary_name.values,index=writer_director_df.nconst).to_dict()
writer_director_dict

{'nm0062070': 'Bruce Baum',
 'nm0062879': 'Ruel S. Bayani',
 'nm0064023': 'Bryan Beasley',
 'nm0065847': 'Michael Frost Beckner',
 'nm0066163': 'Arnaud Bedouët',
 'nm0066268': 'Steve Mitchell Beebe',
 'nm0067234': 'Hans Beimler',
 'nm0068170': 'Dylan Bell',
 'nm0068874': 'Hava Kohav Beller',
 'nm0070482': 'Joel Bender',
 'nm0070822': 'Terry Benedict',
 'nm0072476': 'Doug Benson',
 'nm0074009': 'Richard Berge',
 'nm0075049': 'Urban Bergsten',
 'nm0075666': 'Joe Berlinger',
 'nm0077067': 'Jamie Bernstein',
 'nm0080787': 'Dusty Bias',
 'nm0081060': 'Grace Cary Bickley',
 'nm0081133': 'Adrienne Biddle',
 'nm0081516': 'Ric Esther Bienstock',
 'nm0081702': 'Claudio Bigagli',
 'nm0082154': 'Miro Bilbrough',
 'nm0083767': 'Fernando Birri',
 'nm0085316': 'James Black',
 'nm0086051': 'Bob Blagden',
 'nm0087190': 'Maurice Blanchot',
 'nm0087595': 'Jamie Blanks',
 'nm0087933': 'Jacek Blawut',
 'nm0088531': 'Ryan Bliss',
 'nm0088888': 'Eric Blom',
 'nm0089850': 'Lars Blumers',
 'nm0090847': 'Roberto Bodegas',
 'nm0091773': 'Holt Boggs',
 'nm0092526': 'David Christopher Loya',
 'nm0093284': 'Aleksandr Bokovikov',
 'nm0093674': 'Arcangelo Bonaccorso',
 'nm0094612': 'Daryl Bonilla',
 'nm0094754': 'Emmanuelle Bonmariage',
 'nm0094756': 'Manu Bonmariage',
 'nm0097788': 'Stephan Bosch',
 'nm0098545': 'Marie Boti',
 'nm0099797': 'Pascal Bourdiaux',
 'nm0099841': 'Gilles Bourdos',
 'nm0099922': 'Pierre Bourgeois',
 'nm0099996': 'Joelle Bourjolly',
 'nm0100311': 'Daniel Bouthillette',
 'nm0100556': 'Raoul Bova',
 'nm0101047': 'David Bowers',
 'nm0101055': 'George Bowers',
 'nm0101248': 'Peter Bowles',
 'nm0102070': 'Manu Boyer',
 'nm0103187': 'Dan Bradley',
 'nm0103262': 'James Allen Bradley',
 'nm0104309': 'Joyce Branagh',
 'nm0104373': 'Taylor Branch',
 'nm0104567': 'Madeline Brandeis',
 'nm0105723': 'Bettina Braun',
 'nm0105914': 'Sharon Brauner',
 'nm0107428': 'Joshua Earl Brennand',
 'nm0109400': 'Mariola Brillowska',
 'nm0111127': 'Robert Bröllochs',
 'nm0111665': 'Simon Brook',
 'nm0111701': 'Haynes Brooke',
 'nm0112678': 'Christopher Broughton',
 'nm0112892': 'Kelley Brower',
 'nm0113819': 'Jeffrey D. Brown',
 'nm0114399': 'Paul Brown',
 'nm0115088': 'Turner Browne',
 'nm0115234': 'Johnathan Brownlee',
 'nm0115262': 'Tony Brownrigg',
 'nm0115638': 'Florentine Bruck',
 'nm0116263': 'Francesco Bruni',
 'nm0118741': 'Andre Buckner',
 'nm0118975': 'Tom Buderwitz',
 'nm0119109': 'Christiane Büchner',
 'nm0119287': 'Jeanette B. Milio',
 'nm0120332': 'David Bunce',
 'nm0120814': 'Noël Burch',
 'nm0120816': 'Ron Burch',
 'nm0121708': 'James Burke',
 'nm0121966': 'Helen McCready',
 'nm0122344': 'Charles Burnett',
 'nm0122379': 'Jim Burnett',
 'nm0122703': 'James C. Burns',
 'nm0123385': 'Sid Burston',
 'nm0125336': 'Jez Butterworth',
 'nm0127202': 'Sigve Bøe',
 'nm0128212': 'Anne-Marie Cadieux',
 'nm0128230': 'Elia Enid Cadilla',
 'nm0128464': 'Eliane Caffé',
 'nm0130957': 'Juan Manuel Calvo',
 'nm0130991': 'Salvador Calvo',
 'nm0131563': 'Duncan Cameron',
 'nm0132168': 'John W. Campbell Jr.',
 'nm0132631': 'Ken Campbell',
 'nm0132962': 'Luc Campeau',
 'nm0133253': 'Jorge Campos',
 'nm0133426': 'Mario Camus',
 'nm0135394': 'Vinicio Capossela',
 'nm0135952': 'Nae Caranfil',
 'nm0136775': 'Peter Care',
 'nm0136996': 'Mark Carey',
 'nm0137365': 'Catherine Carlen',
 'nm0138701': 'Valentina Carnelutti',
 'nm0138708': 'Kathryn Carner',
 'nm0139605': 'Neal Marshall Stevens',
 'nm0140087': 'Ricardo Carrasco',
 'nm0141682': 'Jason Carter',
 'nm0143819': 'Michaela Caspar',
 'nm0144291': 'Bill Cassinelli',
 'nm0145518': 'David Castro',
 'nm0146341': 'Peter Cattaneo',
 'nm0147332': 'Óscar del Caz',
 'nm0148235': 'Michael Cencig',
 'nm0149083': 'Ceesepe',
 'nm0150850': 'Pak-Cheung Chan',
 'nm0150977': 'Kin Chung Chan',
 'nm0151189': 'Ameet Chana',
 'nm0151733': 'Jin Jang',
 'nm0152594': 'Crystal Chappell',
 'nm0153263': 'César Charlone',
 'nm0153265': 'Alexandre Charlot',
 'nm0154833': 'Tatiana Chekhova',
 'nm0154845': 'Jesus Chediak',
 'nm0155536': 'Andy Cheng',
 'nm0156286': 'Jacques Chessex',
 'nm0156507': 'Kwok Kuen Cheung',
 'nm0157019': 'Piero Chiara',
 'nm0157787': 'Stephen Chin',
 'nm0159087': 'Thomas Chong',
 'nm0161809': 'Anna Maria Cianciulli',
 'nm0161834': 'Derek Cianfrance',
 'nm0165159': 'Kevin Clash',
 'nm0166394': 'Dimitri de Clercq',
 'nm0167079': 'Chuck Close',
 'nm0167086': 'Eric Close',
 'nm0167708': 'David Coatsworth',
 'nm0167872': 'Sherry Coben',
 'nm0168143': 'Chad Addison',
 'nm0170504': 'Clifton Ko',
 'nm0171015': 'Dominic Coleman',
 'nm0171474': 'Lewis Colick',
 'nm0171847': 'Marco Colli',
 'nm0172830': 'Carlo Collodi',
 'nm0172858': 'Alex Colls',
 'nm0174551': 'Wilson Coneybeare',
 'nm0175768': 'Christine Conradt',
 'nm0176787': 'T. Michael Conway',
 'nm0177827': 'Pascal',
 'nm0177836': 'Adam Cooper',
 'nm0178226': 'Lucy Sumner',
 'nm0178376': 'Scott Cooper',
 'nm0178910': 'Roman Coppola',
 'nm0180083': 'Jon Corn',
 'nm0187523': 'Mario Crespo',
 'nm0187747': 'Reg Cribb',
 'nm0188266': 'Anthony Crivello',
 'nm0188687': 'Gail Cronauer',
 'nm0189589': 'Steven Crowder',
 'nm0190467': 'Soliman Cruz',
 'nm0190597': 'Alexandra La Roche',
 'nm0190988': 'Nicolas Cuche',
 'nm0191446': 'Charles E. Cullen',
 'nm0191974': 'Tony Cummings',
 'nm0192409': 'Noel Cunningham',
 'nm0192416': 'Patrick Cunningham',
 'nm0255528': 'Danae Elon',
 'nm0256079': 'Matt Ember',
 'nm0256779': 'Michael Ende',
 'nm0258390': 'Jack Epps Jr.',
 'nm0259304': 'Anna Croneman',
 'nm0259693': 'Franz Ernst',
 'nm0261489': 'Steven Esteb',
 'nm0261498': 'Alberto Esteban',
 'nm0261685': 'Jacinto Esteva',
 'nm0262125': 'Treva Etienne',
 'nm0262699': 'Dean Evans',
 'nm0265314': 'Stewart Faichney',
 'nm0265856': 'Francesco Falaschi',
 'nm0266088': 'Susan Fales-Hill',
 'nm0267043': 'Nazanin Farahani',
 'nm0267309': 'James Fargo',
 'nm0267691': 'William Farley',
 'nm0269260': 'Lauren Faust',
 'nm0269329': 'Anne-Marie Faux',
 'nm0270531': 'Fritz Feick',
 'nm0272563': 'Niall Ferguson',
 'nm0272626': 'Tim Ferguson',
 'nm0272714': 'Peter Ferland',
 'nm0273644': 'Mariano Fernández',
 'nm0274262': 'Laurence Ferreira Barbosa',
 'nm0274516': 'Chris Ferrence',
 'nm0275651': 'Niv Fichman',
 'nm0276161': 'Noel Fielding',
 'nm0278957': 'Ian Fischer',
 'nm0282147': 'Graham Fletcher-Cook',
 'nm0283698': 'Johannes Flütsch',
 'nm0283763': 'Sarah Fodey',
 'nm0283844': 'Peter Schønau Fog',
 'nm0284678': 'João Fonseca',
 'nm0285283': 'Katia Forbert',
 'nm0286465': 'Antonio Fornari',
 'nm0286586': 'Benthe Forrer',
 'nm0289125': 'Louise Fox',
 'nm0289167': 'Neal Fox',
 'nm0289959': 'Fernando Franchi',
 'nm0290475': 'Don Francks',
 'nm0291743': 'Aleksandr Franskevich-Laye',
 'nm0293889': 'Stéphane Freiss',
 'nm0294832': 'Thomas Frickel',
 'nm0295480': 'Will Friedwald',
 'nm0295560': 'David T. Friendly',
 'nm0295818': 'Jane Frisby',
 'nm0295907': 'Michael Frislev',
 'nm0296658': 'Cesare Frugoni',
 'nm0296861': 'E. Max Frye',
 'nm0297109': 'Tobias Frühmorgen',
 'nm0297596': 'Jean Fugère',
 'nm0297858': 'Ayako Fujitani',
 'nm0298184': 'Brook Fuller',
 'nm0299990': 'Laura Gabbert',
 'nm0300903': 'Dan Gagliasso',
 'nm0301642': 'Gabrielle Galanter',
 'nm0301698': 'Giovanni Galasso',
 'nm0302916': 'Guillaume Gallienne',
 'nm0302990': 'Kuki Gallmann',
 'nm0304432': 'Roberts Gannaway',
 'nm0304599': 'Leif Gantvoort',
 'nm0304709': 'Jack Kao',
 'nm0307739': 'Nadine Garner',
 'nm0308186': 'Philip R. Garrett',
 'nm0308243': 'David Garrick',
 'nm0308647': 'Greg Garthe',
 'nm0309469': 'Gilles Gaston-Dreyfus',
 'nm0309864': 'John Gau',
 'nm0310178': 'Katja Gauriloff',
 'nm0310614': 'Julie Gavras',
 'nm0310813': 'James Gay-Rees',
 'nm0311532': 'Grant Gee',
 'nm0311687': 'Anthony Geffen',
 'nm0311702': 'Lotta Geffenblad',
 'nm0312881': 'Toby Genkel',
 'nm0313746': 'Maria Georgiadou',
 'nm0313984': 'Olivier Gérard',
 'nm0315850': 'Hassan Gholizadeh',
 'nm0315917': 'Rabi Ghosh',
 'nm0316230': 'Constantine Giannaris',
 'nm0316264': 'Mario Gianni',
 'nm0316752': 'Jean-Paul Gibeau',
 'nm0316795': 'Alex Gibney',
 'nm0317314': 'Bastiaan Gieben',
 'nm0318098': 'Jo Gilbert',
 'nm0318886': 'Marco Gilles',
 'nm0388578': 'Isa Hoes',
 'nm0391473': 'Aslaug Holm',
 'nm0399011': 'Jun Huang',
 'nm0399326': 'Dave Huber',
 'nm0399344': 'Grischa Huber',
 'nm0400574': 'Dustin Hughes',
 'nm0400864': 'Phil Hughes',
 'nm0403570': 'Emily Hurson',
 'nm0403622': 'Lillian Hurst',
 'nm0404067': 'Eva Husson',
 'nm0404749': 'René Huybrechtse',
 'nm0404931': 'Paul Hyett',
 'nm0405213': 'Zephirin Hymel IV',
 'nm0405605': 'Klaus Härö',
 'nm0405783': 'Tsukasa Hôjô',
 'nm0405784': 'Toomas Hõrak',
 'nm0406167': 'Thomas Hürlimann',
 'nm0406170': 'Alfred Hürmer',
 'nm0408043': 'Hiroyuki Imaishi',
 'nm0408615': 'Gonzalo Infante',
 'nm0410288': 'John Irving',
 'nm0410945': 'Toshirô Ishidô',
 'nm0411229': 'Mai Iskander',
 'nm0411422': 'Daniel Isoppo',
 'nm0411740': 'Seikô Itô',
 'nm0411932': 'Ivan Ivan',
 'nm0416535': 'Greg James',
 'nm0417202': 'Peter Jamison',
 'nm0419541': 'Cezary Jaworski',
 'nm0419796': 'Borys Jaznicki',
 'nm0419829': 'Olivier Jean Marie',
 'nm0420290': 'Glenn Jeffrey',
 'nm0420926': 'Mykel Shannon Jenkins',
 'nm0421898': 'Milenko Jeremic',
 'nm0422151': 'Otto Jespersen',
 'nm0422813': 'Margarita Jimeno',
 'nm0423765': 'Arthur Johansen',
 'nm0423872': 'Vasa',
 'nm0425388': 'Jo Johnson',
 'nm0426062': 'Richard Johnson',
 'nm0426103': 'Robert A. Johnson',
 'nm0426238': 'Simon Johnson',
 'nm0426343': 'Titti Johnson',
 'nm0426500': 'Kurt Johnstad',
 'nm0427277': 'Alain Jomy',
 'nm0427896': 'Dean Jones',
 'nm0428109': 'Gary Jones',
 'nm0429647': 'Bo Jonsson',
 'nm0430485': 'Lal Jose',
 'nm0431172': 'Duane Journey',
 'nm0432375': 'Karin Julsrud',
 'nm0433169': 'Milton Justice',
 'nm0434389': 'Larisa Kadochnikova',
 'nm0435493': 'Marla Kalin',
 'nm0436501': 'Paresh Kamdar',
 'nm0437596': 'Jeff Kanew',
 'nm0437852': 'Lyle Kanouse',
 'nm0438506': 'Shobha Kapoor',
 'nm0439051': 'Roy Karch',
 'nm0439228': 'Sabine Kargesmeier',
 'nm0439302': 'Varuzh Karim-Masihi',
 'nm0440415': 'Lawrence Kasanoff',
 'nm0442151': 'George S. Kaufman',
 'nm0443803': 'Jon Kean',
 'nm0443842': 'David Keane',
 'nm0444096': 'David Keating',
 'nm0445731': 'Michael Keller',
 'nm0446298': 'Daniel Hugh Kelly',
 'nm0448301': 'Robert Kennedy',
 'nm0449216': 'Roeland Kerbosch',
 'nm0450082': 'Ákos Kertész',
 'nm0450815': 'Irwin Keyes',
 'nm0453118': 'Harry Killas',
 'nm0453657': 'Sang-Jin Kim',
 'nm0519449': 'Angelo Longoni',
 'nm0521803': 'Aku Louhimies',
 'nm0522160': 'Guy J. Louthan',
 'nm0522836': 'Rhes Low',
 'nm0523880': 'Alejandro Lubezki',
 'nm0524239': 'Mark Lucas',
 'nm0526000': 'Alicia Luna',
 'nm0526467': 'Johan Lundh',
 'nm0528461': 'Stuart Lynch',
 'nm0528508': 'Laurie Lynd',
 'nm0529150': 'Robert F. Lyons',
 'nm0529456': 'Roberto Lázaro',
 'nm0530727': 'This Lüscher',
 'nm0531348': 'Mark Macauley',
 'nm0531954': 'Toby MacDonald',
 'nm0532531': 'Willow Hale',
 'nm0535277': 'Marcelo Madureira',
 'nm0535702': 'Marat Magambetov',
 'nm0536421': 'Pierre Magny',
 'nm0540139': 'Brendan Malloy',
 'nm0542036': 'Alain Maneval',
 'nm0542624': 'Nitin Manmohan',
 'nm0543890': 'Francisco Manso',
 'nm0545085': 'Scott Marcano',
 'nm0546008': 'Paula Markovitch',
 'nm0546166': 'Philip Marcus',
 'nm0546893': 'Talivaldis Margévics',
 'nm0547613': 'Madalina Marinescu',
 'nm0548591': 'Tamarat Makonnen',
 'nm0549460': 'Publius Vergilius Maro',
 'nm0549560': 'Michi Marosszeky',
 'nm0549766': 'Luisa Marques',
 'nm0550004': 'Leon Marr',
 'nm0558341': 'Anatoliy Mateshko',
 'nm0559105': 'Mate Matisic',
 'nm0560274': 'Hugo Matthysen',
 'nm0561813': 'Ron Maxwell',
 'nm0562830': 'Philippe Maynial',
 'nm0563025': 'Georg Mayrhofer',
 'nm0563987': 'Johnny McAllister',
 'nm0564323': 'Joseph McBride',
 'nm0565596': 'Cady McClain',
 'nm0565847': 'Joshua David McLerran',
 'nm0567162': 'Gerald McCullouch',
 'nm0567976': 'Rocky McDonald',
 'nm0568605': 'Ian McEwan',
 'nm0569785': 'Declan McGrath',
 'nm0570385': 'Stephen McHattie',
 'nm0570682': 'Peter R. McIntosh',
 'nm0570771': 'Joey McIntyre',
 'nm0570795': 'Michael McIntyre',
 'nm0570912': 'Adam McKay',
 'nm0570991': 'Jeffrey McKay',
 'nm0571789': 'Scott W. McKinlay',
 'nm0571952': 'Kate McKinnon',
 'nm0573284': 'James McMillan',
 'nm0573427': 'Ken McMullen',
 'nm0573934': 'Timothy McNeil',
 'nm0574597': 'Donny McTaggart',
 'nm0574929': 'Taylor Mead',
 'nm0576494': 'Umesh Mehra',
 'nm0578128': 'Greg Mellott',
 'nm0579146': 'Michael Mendizza',
 'nm0579726': 'Pierre Mennel',
 'nm0580396': 'Claire Mercier',
 'nm0581890': 'Tod Mesirow',
 'nm0582396': 'Alex Metcalf',
 'nm0582770': 'Barbara Metzlaff',
 'nm0583243': 'Kris Meyer',
 'nm0583289': 'Nana Meyer',
 'nm0583931': 'Joe Miale',
 'nm0584221': 'Thomas Michael',
 'nm0585701': 'Martin Miehe-Renard',
 'nm0654714': 'Hitoshi Ozawa',
 'nm0655575': 'Béla Paczolay',
 'nm0655898': 'Leonardo Padura',
 'nm0656223': 'Jordan Page',
 'nm0656333': 'Ryan Page',
 'nm0657631': 'Stephen Paley',
 'nm0657707': 'Ranjan Palit',
 'nm0657723': 'Jelena Paljan',
 'nm0658482': 'Tony Palmer',
 'nm0659210': 'Dilip Panda',
 'nm0659238': 'Kamlesh Pandey',
 'nm0659490': 'Diego Panich',
 'nm0659892': 'Massimiliano Pantucci',
 'nm0660098': 'Nicol Paone',
 'nm0660234': 'Jou Jou Papailler',
 'nm0660522': 'Jaroslav Papousek',
 'nm0661785': 'Anna Park',
 'nm0662530': 'Ol Parker',
 'nm0662704': 'Will Parker',
 'nm0665535': 'Vincent Paterson',
 'nm0666640': 'Robert Patton-Spruill',
 'nm0667665': 'Charles Paviot',
 'nm0668283': 'Chris Payne Gilbert',
 'nm0671367': 'Perri Peltz',
 'nm0671824': 'Neil Peng',
 'nm0672545': 'Lola Peploe',
 'nm0672865': 'Nathalie Percillier',
 'nm0674078': 'Troy Perkins',
 'nm0674265': 'Yael Perlov',
 'nm0677064': 'Charles Peterson',
 'nm0678199': 'Valeri Petrov',
 'nm0678959': 'Claus Peymann',
 'nm0679026': 'Philippe Peythieu',
 'nm0680250': 'Bill Phillips',
 'nm0680369': 'Doug Phillips',
 'nm0682904': 'Didier Pietri',
 'nm0684460': 'Emil Pinnock',
 'nm0685094': 'Christine Pireaux',
 'nm0686074': 'Alessandro Piva',
 'nm0687861': 'Sabine Pochhammer',
 'nm0687937': 'Eyal Podell',
 'nm0688282': 'John Pogue',
 'nm0688544': 'Manuel Poirier',
 'nm0688636': 'Laura Poitras',
 'nm0688653': 'Bretislav Pojar',
 'nm0689185': 'Mark Polish',
 'nm0690642': 'Edoardo Ponti',
 'nm0693892': 'Manuel Poutte',
 'nm0693956': 'Jon Povill',
 'nm0694249': 'Nick Powell',
 'nm0696049': 'Olga Preobrazhenskaya',
 'nm0696576': 'Jennifer Prettyman',
 'nm0696964': 'John Price',
 'nm0697865': 'Sandra Prinsloo',
 'nm0697910': 'Frank Prinzi',
 'nm0698535': 'Biagio Proietti',
 'nm0698681': 'Greg Proops',
 'nm0698960': 'Caroline Proust',
 'nm0698964': 'Frédéric Proust',
 'nm0699547': 'Emmanuel Prévost',
 'nm0699802': 'Lisa Kirk Colburn',
 'nm0700635': 'Marian Puobis',
 'nm0700800': 'Ron Purdie',
 'nm0701260': 'David Maria Putorti',
 'nm0701354': 'Jean-Philippe Puymartin',
 'nm0702477': 'Edgar Pêra',
 'nm0702741': 'Jacopo Quadri',
 'nm0702863': 'Troy Quane',
 'nm0702929': 'Paul Quarrington',
 'nm0704270': 'Zachary Quinto',
 'nm0704664': 'Ilmar Raag',
 'nm0707963': 'Dennison Ramalho',
 'nm0709392': 'Tony Ranasinghe',
 'nm0709561': 'Chris Randall',
 'nm0710850': 'Jerry Rapp',
 'nm0711838': 'Benjamin Ratner',
 'nm0713604': 'Rahim Razali',
 'nm0713864': 'Nick Read',
 'nm0714414': 'Ron Recasner',
 'nm0714772': 'P. Chandrasekhara Reddy',
 'nm0715916': 'Jerry Rees',
 'nm0716520': 'Dirk Regel',
 'nm0781238': 'Amy Sedaris',
 'nm0783172': 'Andrea Seligmann Silva',
 'nm0783888': 'Peter Sempel',
 'nm0785063': 'John Serge',
 'nm0785968': 'Claudio Sestieri',
 'nm0788698': 'Levon Sharafyan',
 'nm0788916': 'Sanjeev Sharma',
 'nm0789744': 'Greg Shaw',
 'nm0791657': 'Mark Lawson Shepard',
 'nm0791685': 'Tom Shepard',
 'nm0791803': 'John Shepherd',
 'nm0793519': 'Vsevolod Shilovskiy',
 'nm0793640': 'Atsushi Shimizu',
 'nm0795511': 'Kei Shu',
 'nm0798110': 'Jules Hart',
 'nm0800474': 'Alberto Simone',
 'nm0800801': 'Per Simonsson',
 'nm0801521': 'Khosrow Sinai',
 'nm0803890': 'Gustaf Skarsgård',
 'nm0805932': 'April Sloan',
 'nm0807023': 'Natalia Smirnoff',
 'nm0807099': 'Anton Smit',
 'nm0808384': 'Gregory J. Smith',
 'nm0808668': 'Jeffrey D. Smith',
 'nm0809133': 'Llewellyn M. Smith',
 'nm0809753': 'Robert Beaumont',
 'nm0812067': 'João Sodré',
 'nm0812850': 'Giancarlo Soldi',
 'nm0814763': 'Peter Sorcher',
 'nm0815372': 'Koula Sossiadis Kazista',
 'nm0815425': 'Chris Soth',
 'nm0818204': 'Volker Spengler',
 'nm0819733': 'Jon Springer',
 'nm0819908': 'Eric Spudic',
 'nm0820866': 'Gunnar Staalesen',
 'nm0821048': 'Timothy Stack',
 'nm0821813': 'Monica Stambrini',
 'nm0821850': 'Lena Stamm',
 'nm0822216': 'Eric Stange',
 'nm0822521': 'John Stanley',
 'nm0823499': 'Elizabeth Starr',
 'nm0824626': 'Michael Anthony Steele',
 'nm0825748': 'Elyse Steinberg',
 'nm0826305': 'Massimo Stella',
 'nm0826369': 'Martin Stellman',
 'nm0826893': 'Joseph Stephans',
 'nm0827295': 'Michele Stephenson',
 'nm0827694': 'Gabriela Stern',
 'nm0829083': 'Rick Steves',
 'nm0830082': 'Ulrich Stiehm',
 'nm0830224': 'James Still',
 'nm0830269': 'Daniel Stilling',
 'nm0830419': 'R.L. Stine',
 'nm0830738': 'Michael Stock',
 'nm0833616': 'Luke Stratte-McClure',
 'nm0833627': 'Charlie Stratton',
 'nm0833988': 'Martin Strba',
 'nm0834152': 'Sofia Strehlow',
 'nm0834902': 'Robert Stromberg',
 'nm0837808': 'Ondrej Sulaj',
 'nm0837865': 'Asya Suleyeva',
 'nm0838499': 'Martin Sulík',
 'nm0838630': 'Kevin Summerfield',
 'nm0840558': 'Dani Suzuki',
 'nm0843386': 'Johnny Symons',
 'nm0843726': 'Györgyi Szalai',
 'nm0844784': 'José María Sánchez Silva',
 'nm0910807': 'Alan J. Wands',
 'nm0911039': 'Suzanne Wang',
 'nm0911093': 'Jimmy Wang Yu',
 'nm0911477': 'Darren Ward',
 'nm0912711': 'Alex Warren',
 'nm0913741': 'David Wasson',
 'nm0916510': 'Bruce Weber',
 'nm0923312': 'Joshua Wexler',
 'nm0924653': 'Danielle White',
 'nm0925768': 'Paul Whitehouse',
 'nm0927179': 'Virgil Widrich',
 'nm0927600': 'Elie Wiesel',
 'nm0928492': 'Oscar Wilde',
 'nm0929093': 'José Wilker',
 'nm0930064': 'Barry Williams',
 'nm0930595': 'Frank Williams',
 'nm0931251': 'Mark Williams',
 'nm0931285': 'Matt Williams',
 'nm0931426': 'Pat Williams',
 'nm0932810': 'Curt Allen Wilmer',
 'nm0934136': 'Sheree J. Wilson',
 'nm0934867': 'Lucy Winer',
 'nm0934912': 'Jonathan Winfrey',
 'nm0935352': 'Matt Winn',
 'nm0937725': 'Dick Wolf',
 'nm0939584': 'Bret Wood',
 'nm0939669': 'Douglas Wood',
 'nm0940326': 'Jeremy Wooding',
 'nm0940974': 'Peter Woodward',
 'nm0942094': 'Andrew Wreggitt',
 'nm0943104': 'Jing Wu',
 'nm0943262': 'Reinhard Wulf',
 'nm0943458': 'Gerardine Wurzburg',
 'nm0943944': 'Joel D. Wynkoop',
 'nm0944521': 'Fei Xie',
 'nm0944762': 'Reuben Yabuku',
 'nm0945901': 'Svetlana Yancheva',
 'nm0946324': 'Ebru Ceylan',
 'nm0947073': 'Richard Yearwood',
 'nm0947869': 'Irina Evteeva',
 'nm0948097': 'Yinnan Ding',
 'nm0948410': 'Masahiro Yokotani',
 'nm0948770': 'Steve York',
 'nm0949774': 'Kenny Young',
 'nm0950165': 'William Allen Young',
 'nm0951969': 'Dan Zahle',
 'nm0952429': 'Pjer Zalica',
 'nm0953344': 'Mario Zaragoza',
 'nm0956041': 'Marcin Ziebinski',
 'nm0956249': 'Luis Ziembrowski',
 'nm0957103': 'Ilona Ziok',
 'nm0957105': 'Fabrice Ziolkowski',
 'nm0959970': 'Hideaki Ôba',
 'nm0963344': 'John Bunyan',
 'nm0963403': 'Anthony Hall',
 'nm0969044': 'Ethan Dufault',
 'nm0969389': 'David Jeffcock',
 'nm0969637': 'Martín Mainoli',
 'nm0969743': 'Kaveh Moeinfar',
 'nm0970101': 'Sahand Samadian',
 'nm0973729': 'Russ Russo',
 'nm0974205': 'Amanda Boyle',
 'nm0975225': 'Griff Furst',
 'nm0975325': 'Creighton Vero',
 'nm0989043': 'Katy Chevigny',
 'nm0990442': 'Ben Carson',
 'nm0992727': 'Michael Rucker',
 'nm0994028': 'Aymae Sulick',
 'nm0994379': 'Tosca Musk',
 'nm0994477': 'Ken Kaplan',
 'nm0994499': 'Greg Barker',
 'nm0995444': 'Geórgia Costa Araújo',
 'nm0996471': 'Samuel Benchetrit',
 'nm10109536': 'Eliseo Cabrera',
 'nm10110938': 'Dorrill Griffin',
 'nm1011188': 'Lionel Goddard',
 'nm10115302': 'Dhanesh Anand',
 'nm10115487': 'Laurette De Haan',
 'nm10117309': 'Mikhay Rakhmon',
 'nm10117384': 'Manuela Infante',
 'nm1011820': 'Nicole Newnham',
 'nm1012037': 'Alastair Riddell',
 'nm1012246': 'Geoffrey Stebbins',

In [24]:
actor_actress_df = imdb_name_basics_df[imdb_name_basics_df['primary_profession'].str.contains( 'actor|actress', na=False)]
actor_actress_dict =  pd.Series(actor_actress_df.primary_name.values,index=actor_actress_df.nconst).to_dict()
actor_actress_dict

{'nm0062070': 'Bruce Baum',
 'nm0063198': 'Bayou',
 'nm0063750': 'Lindsay Beamish',
 'nm0066093': 'Ahmad Bedair',
 'nm0066163': 'Arnaud Bedouët',
 'nm0066897': 'Mohammad-Ali Behboudi',
 'nm0067845': 'Sondos Belhassen',
 'nm0067983': 'Krunoslav Belko',
 'nm0068170': 'Dylan Bell',
 'nm0069131': 'Gregg Bello',
 'nm0069225': 'Gavin Bellour',
 'nm0069757': 'Olga Belyavskaya',
 'nm0069990': 'Jorge Ben Jor',
 'nm0070216': 'John Paul Fedele',
 'nm0071116': 'Valérie Benguigui',
 'nm0072476': 'Doug Benson',
 'nm0073146': 'Gina Lola Benzina',
 'nm0073381': 'Roxana Berco',
 'nm0073426': 'Laxmikant Berde',
 'nm0074445': 'Jean-François Bergeron',
 'nm0075049': 'Urban Bergsten',
 'nm0076139': 'Andrée Bernard',
 'nm0077067': 'Jamie Bernstein',
 'nm0081060': 'Grace Cary Bickley',
 'nm0081255': 'Andreas Bieber',
 'nm0081702': 'Claudio Bigagli',
 'nm0081735': 'Andrew Bigelow',
 'nm0082112': 'Jay Bilas',
 'nm0082302': 'Billa',
 'nm0082740': 'Shirin Bina',
 'nm0083271': 'Leila Birch',
 'nm0083605': 'David Birkin',
 'nm0083767': 'Fernando Birri',
 'nm0085193': 'Bill Black',
 'nm0085316': 'James Black',
 'nm0086205': 'Bre Blair',
 'nm0086611': 'Julia Blake',
 'nm0087103': 'Saga Blanchard',
 'nm0087913': 'Jean Blaute',
 'nm0088098': 'Jonah Blechman',
 'nm0089896': 'Colin Blunstone',
 'nm0090420': 'Alexander Boboschewski',
 'nm0091773': 'Holt Boggs',
 'nm0092307': 'Nicolas de Boiscuillé',
 'nm0093109': 'Don Bolles',
 'nm0093174': 'Ryan Bollman',
 'nm0093284': 'Aleksandr Bokovikov',
 'nm0093589': 'Matt Bomer',
 'nm0094438': 'Tae-gyu Bong',
 'nm0094612': 'Daryl Bonilla',
 'nm0094754': 'Emmanuelle Bonmariage',
 'nm0095089': 'Françoise Bonnot',
 'nm0096073': 'Óscar Borda',
 'nm0097788': 'Stephan Bosch',
 'nm0097833': 'João Bosco',
 'nm0098327': 'Andy Boswell',
 'nm0098583': 'Claudio Botosso',
 'nm0099134': 'Jacques Boudet',
 'nm0100556': 'Raoul Bova',
 'nm0100854': 'Jeremy Bowen',
 'nm0100865': 'Jon Bowen',
 'nm0101055': 'George Bowers',
 'nm0101248': 'Peter Bowles',
 'nm0101952': 'Wayne Boyd',
 'nm0102744': 'Diana Bracho',
 'nm0103187': 'Dan Bradley',
 'nm0104185': 'Kicki Bramberg',
 'nm0104309': 'Joyce Branagh',
 'nm0105779': 'Heinz-Josef Braun',
 'nm0105914': 'Sharon Brauner',
 'nm0106040': 'Noelia Bravo Herrera',
 'nm0106979': 'Michal Breitenwald',
 'nm0107428': 'Joshua Earl Brennand',
 'nm0109400': 'Mariola Brillowska',
 'nm0110262': 'Werner Brix',
 'nm0111701': 'Haynes Brooke',
 'nm0112678': 'Christopher Broughton',
 'nm0113427': 'Don Brown',
 'nm0114441': 'Philip Martin Brown',
 'nm0114698': 'Stephen Joel Brown',
 'nm0115143': 'Alistair Browning',
 'nm0115262': 'Tony Brownrigg',
 'nm0116263': 'Francesco Bruni',
 'nm0116737': 'Cory Brusseau',
 'nm0116978': 'Lindsay Bryan',
 'nm0117863': 'Maria Grazia Buccella',
 'nm0118047': 'Big Youth',
 'nm0118741': 'Andre Buckner',
 'nm0120263': 'Bruno Bulté',
 'nm0120284': 'Andy Bumatai',
 'nm0120332': 'David Bunce',
 'nm0121620': 'Carlease Burke',
 'nm0121731': 'Joe Michael Burke',
 'nm0121903': 'Willi Burke',
 'nm0121966': 'Helen McCready',
 'nm0122635': 'David Burns',
 'nm0122703': 'James C. Burns',
 'nm0123385': 'Sid Burston',
 'nm0123896': 'Gerald Busby',
 'nm0124502': 'Mathieu Bisson',
 'nm0125336': 'Jez Butterworth',
 'nm0125588': 'Agata Buzek',
 'nm0125608': 'Natalya Buzko',
 'nm0125661': 'Paolo Buzzurro',
 'nm0126173': 'Elianne Byrne',
 'nm0126478': 'Margaretha Byström',
 'nm0127067': 'Wolfgang Böhmer',
 'nm0127202': 'Sigve Bøe',
 'nm0127313': 'Andrea Bürgin',
 'nm0128212': 'Anne-Marie Cadieux',
 'nm0128230': 'Elia Enid Cadilla',
 'nm0128328': 'Gary Cady',
 'nm0129807': 'Zoe Caldwell',
 'nm0130385': 'Monica Calle',
 'nm0131252': 'Iberê Camargo',
 'nm0131347': 'James Camblin',
 'nm0132265': 'Bryce Campbell',
 'nm0132631': 'Ken Campbell',
 'nm0133658': 'Aurora Cancian',
 'nm0133843': 'Vlastimil Canek',
 'nm0134357': 'Roberto Cano',
 'nm0135667': 'Anita Caprioli',
 'nm0135952': 'Nae Caranfil',
 'nm0136927': 'Danny Carey',
 'nm0137365': 'Catherine Carlen',
 'nm0138701': 'Valentina Carnelutti',
 'nm0138708': 'Kathryn Carner',
 'nm0138966': 'Jean Carol',
 'nm0140179': 'Ricardo Carrión',
 'nm0140510': 'Marcela Carrillo',
 'nm0141324': 'Silas Carson',
 'nm0141450': 'Alex Carter',
 'nm0141682': 'Jason Carter',
 'nm0142808': 'Diego Casale',
 'nm0143819': 'Michaela Caspar',
 'nm0143873': 'Dorin Caspi',
 'nm0144039': 'Cécile Cassel',
 'nm0144291': 'Bill Cassinelli',
 'nm0144887': 'Virgílio Castelo',
 'nm0145518': 'David Castro',
 'nm0145813': 'Bobby Catalano',
 'nm0145951': 'Antonio Catania',
 'nm0147975': 'Jaime Celedón',
 'nm0148234': 'Julia Cencig',
 'nm0149083': 'Ceesepe',
 'nm0149286': 'Janusz Chabior',
 'nm0150850': 'Pak-Cheung Chan',
 'nm0151189': 'Ameet Chana',
 'nm0152594': 'Crystal Chappell',
 'nm0154052': 'Vasanthi Chathurani',
 'nm0154632': 'Ricardo Chavira',
 'nm0154833': 'Tatiana Chekhova',
 'nm0154845': 'Jesus Chediak',
 'nm0155389': 'Terry Chen',
 'nm0155978': 'Natalya Chernyavskaya',
 'nm0156444': 'Cecilia Cheung',
 'nm0157019': 'Piero Chiara',
 'nm0158285': 'Mary-Colin Chisholm',
 'nm0158979': 'Fabien Chombart',
 'nm0159535': 'Debesh Roy Chowdhury',
 'nm0160100': 'Troy Christian',
 'nm0160463': 'Bob Christo',
 'nm0161075': 'Babs Chula',
 'nm0161809': 'Anna Maria Cianciulli',
 'nm0162281': 'Enzo Cilenti',
 'nm0162333': 'Mario Cimarro',
 'nm0162486': 'Gigliola Cinquetti',
 'nm0162646': "Francesca Cipriani d'Altorio",
 'nm0162945': 'Ludovít Cittel',
 'nm0163748': 'Candy Clark',
 'nm0163984': 'Graham Clarke',
 'nm0164667': 'Billy Clarke',
 'nm0164797': 'J.R. Clarke',
 'nm0165159': 'Kevin Clash',
 'nm0165557': 'Pamela Clay',
 'nm0166921': 'Hillary Clinton',
 'nm0167079': 'Chuck Close',
 'nm0167086': 'Eric Close',
 'nm0168143': 'Chad Addison',
 'nm0170087': 'Flora Coker',
 'nm0170504': 'Clifton Ko',
 'nm0171015': 'Dominic Coleman',
 'nm0172701': 'Suzanne Collins',
 'nm0173105': 'Héctor Colomé',
 'nm0175796': 'Brendan Conroy',
 'nm0176444': 'Paolo Contis',
 'nm0176775': 'Sally Conway',
 'nm0177566': 'Tre Cool',
 'nm0177738': 'Daniel Coonan',
 'nm0177827': 'Pascal',
 'nm0178376': 'Scott Cooper',
 'nm0179562': 'Scott Cordes',
 'nm0179871': 'Steve Corino',
 'nm0180431': 'Nick Cornish',
 'nm0180467': 'Blanche Cornwall',
 'nm0182803': 'Suzy Cote',
 'nm0183039': 'Jason Cottle',
 'nm0186151': 'Grant Cramer',
 'nm0186677': 'Lorella Cravotta',
 'nm0186746': 'Dominique Crawford',
 'nm0186767': 'Filipe Crawford',
 'nm0186890': 'Marc Crawford',
 'nm0187634': 'Laura Cret',
 'nm0187695': 'Martin Crewes',
 'nm0187747': 'Reg Cribb',
 'nm0188266': 'Anthony Crivello',
 'nm0188687': 'Gail Cronauer',
 'nm0188776': 'Kevin Cronin',
 'nm0189589': 'Steven Crowder',
 'nm0190467': 'Soliman Cruz',
 'nm0190744': 'Marton Csokas',
 'nm0190988': 'Nicolas Cuche',
 'nm0190996': 'Gaspare Cucinella',
 'nm0191974': 'Tony Cummings',
 'nm0192409': 'Noel Cunningham',
 'nm0256105': 'Tine Embrechts',
 'nm0256779': 'Michael Ende',
 'nm0257188': 'Kim Engelbrecht',
 'nm0259490': 'Arif Erkin Güzelbeyoglu',
 'nm0260554': 'Juliet Esey Joseph',
 'nm0260695': 'Habib Esmaili',
 'nm0261685': 'Jacinto Esteva',
 'nm0261800': 'Daniel Estrada',
 'nm0262125': 'Treva Etienne',
 'nm0262471': 'Stefanie Evangelista',
 'nm0265314': 'Stewart Faichney',
 'nm0265668': 'Donald Faison',
 'nm0266088': 'Susan Fales-Hill',
 'nm0266410': 'Dennis MaGee Fallon',
 'nm0267043': 'Nazanin Farahani',
 'nm0269077': 'James Faulkner',
 'nm0269616': 'Tamara Fay',
 'nm0270625': 'JJ Feild',
 'nm0272626': 'Tim Ferguson',
 'nm0273972': 'Francesca Ferrara',
 'nm0274262': 'Laurence Ferreira Barbosa',
 'nm0275002': 'Rafael Ferro',
 'nm0275651': 'Niv Fichman',
 'nm0276161': 'Noel Fielding',
 'nm0276726': 'Mauricio Figueroa',
 'nm0277525': 'Deborah Findlay',
 'nm0282147': 'Graham Fletcher-Cook',
 'nm0282747': 'Alejandra Flores',
 'nm0283253': 'Wendee Lee',
 'nm0284049': 'Joe Folau',
 'nm0284259': 'Felipe Folgosi',
 'nm0284541': 'Brian Fong',
 'nm0284678': 'João Fonseca',
 'nm0286465': 'Antonio Fornari',
 'nm0286586': 'Benthe Forrer',
 'nm0290475': 'Don Francks',
 'nm0290969': 'Jason David Frank',
 'nm0291460': 'Joe Franklin',
 'nm0291743': 'Aleksandr Franskevich-Laye',
 'nm0292263': 'Xuan Fraser',
 'nm0293889': 'Stéphane Freiss',
 'nm0295505': 'Antonio Friello',
 'nm0295861': 'Jacquelyn Frisco',
 'nm0297076': 'Samuel Fröler',
 'nm0297858': 'Ayako Fujitani',
 'nm0298020': 'Seizô Fukumoto',
 'nm0298184': 'Brook Fuller',
 'nm0298335': 'Robert Welch',
 'nm0299174': 'Kôji Furuhata',
 'nm0299222': 'Ikkô Furuya',
 'nm0299228': 'Tôru Furuya',
 'nm0301642': 'Gabrielle Galanter',
 'nm0302916': 'Guillaume Gallienne',
 'nm0304599': 'Leif Gantvoort',
 'nm0304709': 'Jack Kao',
 'nm0307358': 'Gerardo Gargiulo',
 'nm0307739': 'Nadine Garner',
 'nm0308651': 'Chris Gartin',
 'nm0309168': 'Piotr Gasowski',
 'nm0309469': 'Gilles Gaston-Dreyfus',
 'nm0310614': 'Julie Gavras',
 'nm0312586': 'Nikki Gemmell',
 'nm0312981': 'Vicente Genovés',
 'nm0313144': 'Martin Gentles',
 'nm0313388': 'Christopher Dunn George',
 'nm0313534': 'Melissa George',
 'nm0313746': 'Maria Georgiadou',
 'nm0313984': 'Olivier Gérard',
 'nm0315917': 'Rabi Ghosh',
 'nm0316230': 'Constantine Giannaris',
 'nm0316752': 'Jean-Paul Gibeau',
 'nm0317302': 'Irit Gidron',
 'nm0317798': 'João Gil',
 'nm0319010': 'Aden Gillett',
 'nm0388486': 'Willy Hoeller',
 'nm0388578': 'Isa Hoes',
 'nm0388954': 'Jerry Hoffman',
 'nm0391722': 'Kjersti Holmen',
 'nm0393702': 'Elissa Dulce Hoopai',
 'nm0393855': 'Robert Hooven',
 'nm0394348': 'Eliana Miglio',
 'nm0395587': 'Derek Horton',
 'nm0399326': 'Dave Huber',
 'nm0399344': 'Grischa Huber',
 'nm0400864': 'Phil Hughes',
 'nm0403570': 'Emily Hurson',
 'nm0403622': 'Lillian Hurst',
 'nm0403977': 'Nazim Hussain',
 'nm0404067': 'Eva Husson',
 'nm0404693': 'Brody Hutzler',
 'nm0405213': 'Zephirin Hymel IV',
 'nm0405784': 'Toomas Hõrak',
 'nm0406367': 'Peter Iasillo Jr.',
 'nm0406818': 'John Idakitis',
 'nm0407527': 'Hiroshi Yanaka',
 'nm0408985': 'Jack Ingram',
 'nm0409219': 'Virginia Innocenti',
 'nm0409336': 'Daniel Inouye',
 'nm0410288': 'John Irving',
 'nm0410655': 'Ewa Telega',
 'nm0410945': 'Toshirô Ishidô',
 'nm0411220': 'Azri Iskandar',
 'nm0411422': 'Daniel Isoppo',
 'nm0411740': 'Seikô Itô',
 'nm0412596': 'Satoko Iwasaki',
 'nm0413382': 'Clydene Jackson',
 'nm0413659': 'Jermaine Jackson',
 'nm0415393': 'Anja Jaenicke',
 'nm0415588': 'Bianca Jagger',
 'nm0416253': 'Adam James',
 'nm0416266': 'Aliza James',
 'nm0416535': 'Greg James',
 'nm0418877': 'John Jarratt',
 'nm0419796': 'Borys Jaznicki',
 'nm0420290': 'Glenn Jeffrey',
 'nm0420926': 'Mykel Shannon Jenkins',
 'nm0421898': 'Milenko Jeremic',
 'nm0422151': 'Otto Jespersen',
 'nm0422659': 'Gang Jiao',
 'nm0423031': 'Néstor Jiménez',
 'nm0423486': 'Slobodan Jocic',
 'nm0423872': 'Vasa',
 'nm0425777': 'Matt Johnson',
 'nm0426062': 'Richard Johnson',
 'nm0427277': 'Alain Jomy',
 'nm0428429': 'John Paul Jones',
 'nm0428856': 'Mickey Jones',
 'nm0429094': 'Rhys Parry Jones',
 'nm0429236': 'Shaw Jones',
 'nm0429944': 'Frank Jordan',
 'nm0430331': 'Dinis Gomes',
 'nm0430485': 'Lal Jose',
 'nm0431681': 'Adelaide João',
 'nm0432375': 'Karin Julsrud',
 'nm0432568': 'Mathias Jung',
 'nm0434389': 'Larisa Kadochnikova',
 'nm0434391': 'Kazue Tsunogae',
 'nm0434651': 'Patrick Teoh',
 'nm0435323': 'Bianca Kajlich',
 'nm0435493': 'Marla Kalin',
 'nm0436076': 'Ariel Kalma',
 'nm0436139': 'Rezija Kalnina',
 'nm0436161': 'Marina Kalogirou',
 'nm0437283': 'Christian Kane',
 'nm0437852': 'Lyle Kanouse',
 'nm0438484': 'Omkar Kapoor',
 'nm0438780': 'Jana Karaivanova',
 'nm0439051': 'Roy Karch',
 'nm0439259': 'Smaragda Karydi',
 'nm0439333': 'Maya Karin',
 'nm0440491': 'Lisa Kaseman',
 'nm0440761': 'Bartek Kasprzykowski',
 'nm0441235': 'Kathryn Kates',
 'nm0441654': 'Cindy Katz',
 'nm0441752': 'Josie Katz',
 'nm0442151': 'George S. Kaufman',
 'nm0442515': 'Andrew Kavadas',
 'nm0442933': 'Ayako Kawasumi',
 'nm0443803': 'Jon Kean',
 'nm0444298': 'Daniel Kedem',
 'nm0444676': 'Rory Keenan',
 'nm0444687': 'Will Keenan',
 'nm0445731': 'Michael Keller',
 'nm0445825': 'Susan Kellermann',
 'nm0446298': 'Daniel Hugh Kelly',
 'nm0446486': 'Jim Kelly',
 'nm0448301': 'Robert Kennedy',
 'nm0448965': 'Bill Kenwright',
 'nm0450815': 'Irwin Keyes',
 'nm0450858': 'Tamar Keynan',
 'nm0451440': 'Bishnu Kharghoria',
 'nm0451561': 'Sachin Khedekar',
 'nm0452159': 'James Kiberd',
 'nm0452385': 'Vinzenz Kiefer',
 'nm0452684': 'Kaleena Kiff',
 'nm0453385': 'Chang-wan Kim',
 'nm0453440': 'Eui-sung Kim',
 'nm0453612': 'Gyu-ri Kim',
 'nm0453657': 'Sang-Jin Kim',
 'nm0519346': 'AG. Longhurst',
 'nm0519449': 'Angelo Longoni',
 'nm0522440': 'Victor Love',
 'nm0522836': 'Rhes Low',
 'nm0524239': 'Mark Lucas',
 'nm0526120': 'Lydia Lunch',
 'nm0526999': 'Bert Luppes',
 'nm0527265': 'René Lussier',
 'nm0527717': 'Vladimir Luxuria',
 'nm0529150': 'Robert F. Lyons',
 'nm0529219': 'Hilde Lyrån',
 'nm0532531': 'Willow Hale',
 'nm0533492': 'Allison Mackie',
 'nm0535277': 'Marcelo Madureira',
 'nm0536421': 'Pierre Magny',
 'nm0537248': 'Diane Adelson',
 'nm0538942': 'Laurent Malaquais',
 'nm0539787': 'Cylia Malki',
 'nm0541386': 'Melissa Manchester',
 'nm0542036': 'Alain Maneval',
 'nm0542510': 'Ravindra Mankani',
 'nm0542558': 'Blu Mankuma',
 'nm0542643': 'Andrea Mann',
 'nm0543429': 'Tom Mannion',
 'nm0543895': 'Leonor Manso',
 'nm0544269': 'Michael Manuel',
 'nm0545792': 'Íñigo Marco',
 'nm0546893': 'Talivaldis Margévics',
 'nm0547450': 'Georg Marin',
 'nm0548032': 'Corinne Mariotto',
 'nm0549629': 'Erika Marozsán',
 'nm0549722': 'António Marques',
 'nm0549826': 'Sean Marquette',
 'nm0550366': 'Delfeayo Marsalis',
 'nm0554047': 'Humberto Martins',
 'nm0554112': 'Rita Martins',
 'nm0555296': 'Petra Martínez',
 'nm0555436': 'Marusha',
 'nm0555712': 'Ken Mary',
 'nm0555837': 'Marco Marzocca',
 'nm0557678': 'Grant Masters',
 'nm0558341': 'Anatoliy Mateshko',
 'nm0558426': 'Eric Matheny',
 'nm0559043': 'Paul Matic',
 'nm0559105': 'Mate Matisic',
 'nm0560274': 'Hugo Matthysen',
 'nm0562830': 'Philippe Maynial',
 'nm0562889': 'Magín Mayo',
 'nm0562988': 'Roy Mayorga',
 'nm0563025': 'Georg Mayrhofer',
 'nm0563156': 'Stéphane Mazalaigue',
 'nm0563355': 'Catherine Mazoyer',
 'nm0564323': 'Joseph McBride',
 'nm0564428': 'Ciaran McCabe',
 'nm0565596': 'Cady McClain',
 'nm0565647': 'Zahn McClarnon',
 'nm0565847': 'Joshua David McLerran',
 'nm0567162': 'Gerald McCullouch',
 'nm0567976': 'Rocky McDonald',
 'nm0569223': 'Bill McGill',
 'nm0569337': 'Ted McGinley',
 'nm0570385': 'Stephen McHattie',
 'nm0570749': 'Gerry McIntyre',
 'nm0570771': 'Joey McIntyre',
 'nm0571188': 'Lonette McKee',
 'nm0571373': 'Jon McKenna',
 'nm0571789': 'Scott W. McKinlay',
 'nm0571952': 'Kate McKinnon',
 'nm0573934': 'Timothy McNeil',
 'nm0574929': 'Taylor Mead',
 'nm0578754': 'Oded Menaster',
 'nm0579726': 'Pierre Mennel',
 'nm0579869': 'Nena Menti',
 'nm0580396': 'Claire Mercier',
 'nm0581436': 'Mike Merritt',
 'nm0583763': 'Juan Cristóbal Meza',
 'nm0584031': 'Kathrina Miccio',
 'nm0584221': 'Thomas Michael',
 'nm0584250': 'Yvonne Miklosh',
 'nm0584274': 'Torsten Michaelis',
 'nm0584279': 'Al Michaels',
 'nm0584971': 'Dalia Micheleviciute',
 'nm0654303': 'Andre Owens',
 'nm0654365': 'Gary Owens',
 'nm0654714': 'Hitoshi Ozawa',
 'nm0655575': 'Béla Paczolay',
 'nm0655943': 'Dira Paes',
 'nm0656223': 'Jordan Page',
 'nm0656968': 'Carlos Paiva',
 'nm0658593': 'Sandra Palmeri',
 'nm0659162': 'Sitaram Panchal',
 'nm0659235': 'Hemant Pandey',
 'nm0659927': 'Lalita Panyopas',
 'nm0660098': 'Nicol Paone',
 'nm0660234': 'Jou Jou Papailler',
 'nm0660291': 'Kostas Papanastasiou',
 'nm0661797': 'Kris Park',
 'nm0662704': 'Will Parker',
 'nm0662960': 'James Parks',
 'nm0663678': 'Natasha Parry',
 'nm0664564': 'Nikola Pashov',
 'nm0664570': 'Aleksandr Pashutin',
 'nm0664738': 'Elsa Pasquier',
 'nm0665143': 'Corinne Pastout',
 'nm0665535': 'Vincent Paterson',
 'nm0668283': 'Chris Payne Gilbert',
 'nm0669246': 'Ellis Pearson',
 'nm0671072': 'Carolina Pelleritti',
 'nm0671367': 'Perri Peltz',
 'nm0671526': 'Luis Fernando Peña',
 'nm0671567': 'Michael Peña',
 'nm0671824': 'Neil Peng',
 'nm0672545': 'Lola Peploe',
 'nm0672784': 'Sabitha Perara',
 'nm0673221': 'Teca Pereira',
 'nm0673747': 'Eric Perrodin',
 'nm0673892': 'Brian Perkins',
 'nm0674101': 'Lee Perkins',
 'nm0677546': 'Aurélia Petit',
 'nm0678061': 'Richard Petrocelli',
 'nm0678199': 'Valeri Petrov',
 'nm0678648': 'Brian Pettifer',
 'nm0678959': 'Claus Peymann',
 'nm0679026': 'Philippe Peythieu',
 'nm0679690': 'Chrystee Pharris',
 'nm0679904': 'John Philbin',
 'nm0680369': 'Doug Phillips',
 'nm0680884': 'Bill Phillips',
 'nm0682986': 'Dominique Pifarely',
 'nm0682999': 'Cara Pifko',
 'nm0684460': 'Emil Pinnock',
 'nm0687509': 'Rosalind Plowright',
 'nm0687937': 'Eyal Podell',
 'nm0688400': 'Gergely Pohárnok',
 'nm0688544': 'Manuel Poirier',
 'nm0689185': 'Mark Polish',
 'nm0690290': 'Pere Ponce',
 'nm0691088': 'Braxton Pope',
 'nm0692629': 'Posdnuos',
 'nm0695594': 'Praveen',
 'nm0696049': 'Olga Preobrazhenskaya',
 'nm0696576': 'Jennifer Prettyman',
 'nm0697865': 'Sandra Prinsloo',
 'nm0698681': 'Greg Proops',
 'nm0698960': 'Caroline Proust',
 'nm0698964': 'Frédéric Proust',
 'nm0700856': 'James Purefoy',
 'nm0700909': 'Linda Purl',
 'nm0701354': 'Jean-Philippe Puymartin',
 'nm0702580': 'Q-Tip',
 'nm0702671': 'Qinqin Li',
 'nm0703013': 'Van Quattro',
 'nm0704270': 'Zachary Quinto',
 'nm0704664': 'Ilmar Raag',
 'nm0706095': 'Raekwon',
 'nm0707427': 'Zen Kajihara',
 'nm0709389': 'Douglas Ranasinghe',
 'nm0709392': 'Tony Ranasinghe',
 'nm0709561': 'Chris Randall',
 'nm0711503': 'Steve Rassin',
 'nm0711838': 'Benjamin Ratner',
 'nm0712954': 'Ola Ray',
 'nm0713604': 'Rahim Razali',
 'nm0714414': 'Ron Recasner',
 'nm0715093': 'Siobhan Redmond',
 'nm0715916': 'Jerry Rees',
 'nm0781238': 'Amy Sedaris',
 'nm0784603': 'Daniele Sepe',
 'nm0785063': 'John Serge',
 'nm0785546': 'Indhira Serrano',
 'nm0785612': 'Roly Serrano',
 'nm0785968': 'Claudio Sestieri',
 'nm0788415': 'Shao Tung Chou',
 'nm0788509': 'George Shapiro',
 'nm0788698': 'Levon Sharafyan',
 'nm0788916': 'Sanjeev Sharma',
 'nm0789481': 'Ed Shaughnessy',
 'nm0790011': 'Tracy Shaw',
 'nm0791803': 'John Shepherd',
 'nm0792069': 'Peter Sherayko',
 'nm0793519': 'Vsevolod Shilovskiy',
 'nm0794358': 'Shirô Tsubuyaki',
 'nm0798110': 'Jules Hart',
 'nm0798944': 'Mark Silverman',
 'nm0800671': 'Evgeniya Simonova',
 'nm0802111': 'Dileep Singh Rathore',
 'nm0802183': 'Neetu Singh',
 'nm0802335': 'Tommy Singleton',
 'nm0802757': 'Edoardo Siravo',
 'nm0803059': 'Sonny Sison',
 'nm0803890': 'Gustaf Skarsgård',
 'nm0804136': 'Joey Skidmore',
 'nm0804342': 'Per Skjølsvik',
 'nm0805932': 'April Sloan',
 'nm0806968': 'Michael Smiley',
 'nm0807741': 'Cliff Everett Smith',
 'nm0810358': "Willie 'Big Eyes' Smith",
 'nm0811253': 'Dan Snow',
 'nm0812067': 'João Sodré',
 'nm0812172': 'Gisella Sofio',
 'nm0812857': 'Dave Soldier',
 'nm0815425': 'Chris Soth',
 'nm0816978': 'Donita Sparks',
 'nm0817375': 'Michael Spears',
 'nm0818204': 'Volker Spengler',
 'nm0818281': 'Alessandro Sperduti',
 'nm0818687': 'Alejandro Speitzer',
 'nm0819908': 'Eric Spudic',
 'nm0820967': 'Jeremy Stacey',
 'nm0821048': 'Timothy Stack',
 'nm0821850': 'Lena Stamm',
 'nm0822974': 'Nicola Stapleton',
 'nm0823149': 'Craig Stark',
 'nm0823445': 'Dimitris Starovas',
 'nm0823499': 'Elizabeth Starr',
 'nm0824103': 'Barry Steadman',
 'nm0824626': 'Michael Anthony Steele',
 'nm0824680': 'Terry Steele',
 'nm0824852': 'Henriette Steenstrup',
 'nm0825045': 'Lidija Stevanovic',
 'nm0826433': 'Katharina Stemberger',
 'nm0827287': 'Marc Stephenson',
 'nm0827694': 'Gabriela Stern',
 'nm0829083': 'Rick Steves',
 'nm0829134': 'Belinda Stewart-Wilson',
 'nm0830419': 'R.L. Stine',
 'nm0830738': 'Michael Stock',
 'nm0831099': 'Isabelle Stoffel',
 'nm0831104': 'Royston Stoffels',
 'nm0831376': 'Nelle Stokes',
 'nm0831613': 'André Stolz',
 'nm0832705': 'Luciano Storti',
 'nm0833616': 'Luke Stratte-McClure',
 'nm0833627': 'Charlie Stratton',
 'nm0834152': 'Sofia Strehlow',
 'nm0837112': 'Richard Suckle',
 'nm0837700': 'Sukanya',
 'nm0837875': 'Fernando Sulichin',
 'nm0838499': 'Martin Sulík',

In [26]:
id_title_dict =  pd.Series(imdb_title_basics_df.movie.values,index=imdb_title_basics_df.tconst).to_dict()
id_title_dict

{'tt0063540': 'Sunghursh',
 'tt0066787': 'One Day Before the Rainy Season',
 'tt0069049': 'The Other Side of the Wind',
 'tt0069204': 'Sabse Bada Sukh',
 'tt0100275': 'The Wandering Soap Opera',
 'tt0111414': 'A Thin Life',
 'tt0112502': 'Bigfoot',
 'tt0137204': 'Joe Finds Grace',
 'tt0139613': 'O Silêncio',
 'tt0144449': 'Nema aviona za Zagreb',
 'tt0146592': 'Pál Adrienn',
 'tt0154039': 'So Much for Justice!',
 'tt0159369': 'Cooper and Hemingway: The True Gen',
 'tt0162942': 'Children of the Green Dragon',
 'tt0170651': 'T.G.M. - osvoboditel',
 'tt0176694': 'The Tragedy of Man',
 'tt0187902': "How Huang Fei-hong Rescued the Orphan from the Tiger's Den",
 'tt0192528': 'Heaven & Hell',
 'tt0230212': 'The Final Journey',
 'tt0247643': 'Los pájaros se van con la muerte',
 'tt0249516': 'Foodfight!',
 'tt0250404': 'Godfather',
 'tt0253093': 'Gangavataran',
 'tt0255820': 'Return to Babylon',
 'tt0262218': 'Akakis mogzauroba',
 'tt0262759': 'Seven Jews from My Class',
 'tt0263814': 'On kadin',
 'tt0276568': 'To Chase a Million',
 'tt0277964': 'Prague: The Restless Heart of Europe',
 'tt0283440': 'Short Time Heroes',
 'tt0285252': "Life's a Beach",
 'tt0285423': 'Abolição',
 'tt0293069': 'Dark Blood',
 'tt0293429': 'Mortal Kombat',
 'tt0297400': 'Snowblind',
 'tt0306058': 'Second Coming',
 'tt0311448': 'Lives No Longer Ours',
 'tt0312305': 'Quantum Quest: A Cassini Space Odyssey',
 'tt0315642': 'Wazir',
 'tt0323808': 'The Wicker Tree',
 'tt0326592': 'The Overnight',
 'tt0326965': 'In My Sleep',
 'tt0328810': 'My Land',
 'tt0329539': 'Rice Girl',
 'tt0330811': 'Regret Not Speaking',
 'tt0330987': 'Tiden är en dröm, del 2',
 'tt0331312': 'This Wretched Life',
 'tt0331314': 'Bunyan and Babe',
 'tt0337692': 'On the Road',
 'tt0337882': 'Blind Sided',
 'tt0337926': 'Chatô - The King of Brazil',
 'tt0339736': 'The Evil Within',
 'tt0346045': 'Transeúntes',
 'tt0357717': 'Haar Jeet',
 'tt0359950': 'The Secret Life of Walter Mitty',
 'tt0360556': 'Fahrenheit 451',
 'tt0364201': 'Aman Ke Farishtey',
 'tt0365545': 'Nappily Ever After',
 'tt0365907': 'A Walk Among the Tombstones',
 'tt0368133': 'The Promise of Perfume',
 'tt0369610': 'Jurassic World',
 'tt0372538': 'Spy',
 'tt0376136': 'The Rum Diary',
 'tt0376479': 'American Pastoral',
 'tt0377981': 'Gnomeo & Juliet',
 'tt0378546': 'The Payback Man',
 'tt0381957': 'Cloud Cuckoo Land',
 'tt0383010': 'The Three Stooges',
 'tt0385887': 'Motherless Brooklyn',
 'tt0393049': "Anderson's Cross",
 'tt0396123': 'Den milde smerte',
 'tt0398286': 'Tangled',
 'tt0400320': 'The Connecticut Kid',
 'tt0401729': 'John Carter',
 'tt0402887': 'Capture the Flag',
 'tt0403645': 'Burnt by the Sun 2',
 'tt0403935': 'Action Jackson',
 'tt0404978': 'Gambit',
 'tt0406282': 'Bubbles',
 'tt0407194': 'Seven Fallen Objects',
 'tt0409379': 'In Secret',
 'tt0409847': 'Cowboys & Aliens',
 'tt0411951': 'Tekken',
 'tt0417610': 'Asleep in the Sun',
 'tt0417750': 'Hempsters: Plant the Seed',
 'tt0419692': 'Disconnect',
 'tt0420293': 'The Stanford Prison Experiment',
 'tt0423474': 'Venus & Vegas',
 'tt0424859': 'The Ninth Cloud',
 'tt0425785': 'El borde del tiempo',
 'tt0426410': 'Beisbol',
 'tt0426566': 'Pots and Pans',
 'tt0427152': 'Dinner for Schmucks',
 'tt0427340': 'Masters of the Universe',
 'tt0427543': 'A Million Little Pieces',
 'tt0429493': 'The A-Team',
 'tt0430524': 'The Rescuer',
 'tt0431021': 'The Possession',
 'tt0432010': 'The Queen of Sheba Meets the Atom Man',
 'tt0433035': 'Real Steel',
 'tt0433397': 'Satin',
 'tt0433533': 'Caleuche: El llamado del Mar',
 'tt0433787': "L'apocalisse delle scimmie",
 'tt0435651': 'The Giver',
 'tt0435761': 'Toy Story 3',
 'tt0436230': 'Mexican Devil',
 'tt0436782': 'A Life in the Death of Joe Meek',
 'tt0437086': 'Alita: Battle Angel',
 'tt0437462': 'Cargo, les hommes perdus.',
 'tt0438973': 'Sealand',
 'tt0439724': 'Moving Target',
 'tt0439801': 'Segurança Nacional',
 'tt0441506': 'Stolen Memories',
 'tt0441779': 'My Nappy Roots: A Journey Through Black Hair-itage',
 'tt0441881': 'Danger Close: The Battle of Long Tan',
 'tt0443272': 'Lincoln',
 'tt0443331': 'Milenge Milenge',
 'tt0443465': 'Before We Go',
 'tt0443533': 'The History of Love',
 'tt0444531': 'Vidas pequeñas',
 'tt0445054': '7 Days',
 'tt0446029': 'Scott Pilgrim vs. the World',
 'tt0446686': 'Dream Street',
 'tt0446792': 'Surviving in L.A.',
 'tt0448022': 'A Bird of the Air',
 'tt0448115': 'Shazam!',
 'tt0448694': 'Puss in Boots',
 'tt0449005': 'Diary of a Bad Lad',
 'tt0451108': 'Mad World',
 'tt0451154': 'The Passing',
 'tt0451201': 'Clawed',
 'tt0451279': 'Wonder Woman',
 'tt0452183': 'Blunt Movie',
 'tt0452664': 'Party Crashers',
 'tt0453562': '42',
 'tt0454155': 'El hada buena - Una fábula peronista',
 'tt0454876': 'Life of Pi',
 'tt0455323': 'Being Flynn',
 'tt0455407': 'The Crazies',
 'tt0455944': 'The Equalizer',
 'tt0457591': 'Memorias del desarrollo',
 'tt0458339': 'Captain America: The First Avenger',
 'tt0458413': 'A Long Way Down',
 'tt0458481': 'Sin City: A Dame to Kill For',
 'tt0459748': 'Generation P',
 'tt0460528': 'One Step Beyond: The True Story of Géraldine Fasnacht',
 'tt0460778': 'Drunkboat',
 'tt0460809': 'The Grasslands',
 'tt0460890': 'The Only Living Boy in New York',
 'tt0460957': "Texxas Jam '78",
 'tt0461336': 'Saving Private Perez',
 'tt0462036': 'Steve Phoenix: The Untold Story',
 'tt0462335': 'High-Rise',
 'tt0462516': 'Satan Hates You',
 'tt0462536': 'Silent Alarm',
 'tt0463311': 'Federal',
 'tt0463960': 'The Devil You Know',
 'tt0464032': 'Guns, Drugs and Dirty Money',
 'tt0464054': 'House at the End of the Drive',
 'tt0464154': 'Piranha 3D',
 'tt0464162': 'Komaram Puli',
 'tt0464891': 'Act Your Age',
 'tt0465637': 'Taken by Force',
 'tt0465760': 'Sensual',
 'tt0466553': 'Golapi Ekhon Bilatey',
 'tt0466893': 'Margaret',
 'tt0469021': 'Alan Partridge',
 'tt0469094': 'Harlem Hostel',
 'tt0469152': 'Smoking/Non-Smoking',
 'tt0469158': 'Platinum Illusions',
 'tt0470752': 'Ex Machina',
 'tt0470936': 'Hot Country, Cold Winter',
 'tt0471042': 'Tower Heist',
 'tt0472181': 'The Smurfs',
 'tt0472399': 'The Mechanic',
 'tt0473032': 'Escape from Heaven',
 'tt0473075': 'Prince of Persia: The Sands of Time',
 'tt0473088': 'Stan',
 'tt0473122': 'Bamboo Shark',
 'tt0473343': 'Cielito lindo',
 'tt0475239': 'Clutch',
 'tt0475290': 'Hail, Caesar!',
 'tt0475360': 'Persona Au Gratin',
 'tt0475983': 'The Deafening Silence of a Very Bright Light',
 'tt0476023': 'Stiffs',
 'tt0477080': 'Unstoppable',
 'tt0477087': 'Sid Bernstein Presents...',
 'tt0477302': 'Extremely Loud & Incredibly Close',
 'tt0478304': 'The Tree of Life',
 'tt0478660': 'El horror de la dama del lago',
 'tt0478970': 'Ant-Man',
 'tt0479051': 'The Greater Meaning of Water',
 'tt0479204': 'Perfect Life',
 'tt0479807': 'Abhishapt',
 'tt0479997': 'Season of the Witch',
 'tt0480239': 'Atlas Shrugged: Part I',
 'tt0480255': 'The Losers',
 'tt0480687': 'Hall Pass',
 'tt0481470': 'Felix Austria!',
 'tt0481499': 'The Croods',
 'tt0482459': 'Bandage',
 'tt0482461': 'Barry Munday',
 'tt0483586': 'Chasing 3000',
 'tt0483740': 'Monkey Man',
 'tt0483839': 'A Woman Is a Woman',
 'tt0484037': 'Gente mala del norte',
 'tt0484828': 'La daga de Rasputín',
 'tt0485061': 'U Want Me 2 Kill Him?',
 'tt0485521': 'Sushi in Suhl',
 'tt0485985': 'Red Tails',
 'tt0486622': 'Making Change',
 'tt0490075': 'Aftermath',
 'tt0490199': 'PrimeMates',
 'tt0490215': 'Silence',
 'tt0490236': 'The Invited',
 'tt0490847': 'Double Tap',
 'tt0491152': 'Something Borrowed',
 'tt0491175': 'Suburbicon',
 'tt0491203': 'Tulip Fever',
 'tt0492389': 'Furry Vengeance',
 'tt0493076': 'Nina',
 'tt0493405': 'CHIPS',
 'tt0493949': 'Ramona and Beezus',
 'tt0494229': 'Good Sharma',
 'tt0495024': 'Bad Blood',
 'tt0495037': 'O Inimigo Sem Rosto',
 'tt0496375': 'Prisoners of the Sun',
 'tt0498351': 'The Hero of Color City',
 'tt0498381': 'Rings',
 'tt0499097': 'Without Remorse',
 'tt0499608': 'Tranced',
 'tt0756727': "Who Is Harry Nilsson (And Why Is Everybody Talkin' About Him?)",
 'tt0758752': 'Love & Other Drugs',
 'tt0762138': 'Syrup',
 'tt0763831': 'A Thousand Words',
 'tt0765446': 'Escape from Planet Earth',
 'tt0765453': 'Have You Seen Me?',
 'tt0765465': 'The Legend of Secret Pass',
 'tt0765485': 'Waste of Space',
 'tt0768187': 'Me and My Umbrella',
 'tt0768222': 'Night of the Templar',
 'tt0770703': "What's Your Number?",
 'tt0770728': 'California Indian',
 'tt0770778': 'King of the Avenue',
 'tt0770802': 'Samsara',
 'tt0770819': 'Till You Get to Baraboo',
 'tt0770828': 'Man of Steel',
 'tt0772175': 'Jersey Justice',
 'tt0772179': 'Kill',
 'tt0774519': 'The Chosen Heaven',
 'tt0775440': 'Cell',
 'tt0775461': 'The Rain Fairy',
 'tt0775489': 'The Illusionist',
 'tt0775543': 'Night Catches Us',
 'tt0780504': 'Drive',
 'tt0780548': 'Kid Cannabis',
 'tt0780625': 'Santorini Blue',
 'tt0780645': 'War of the Dead',
 'tt0780653': 'The Wolfman',
 'tt0781441': 'Escalade',
 'tt0782047': 'Irreversi',
 'tt0783640': 'The Last Full Measure',
 'tt0787442': 'The Attack',
 'tt0787474': 'The Boxtrolls',
 'tt0787524': 'The Man Who Knew Infinity',
 'tt0790628': 'The Incredible Burt Wonderstone',
 'tt0790636': 'Dallas Buyers Club',
 'tt0790653': 'Elliot Loves',
 'tt0790663': 'The First Grader',
 'tt0790724': 'Jack Reacher',
 'tt0790736': 'R.I.P.D.',
 'tt0790770': 'Miles Ahead',
 'tt0790788': 'The Yellow Wallpaper',
 'tt0795459': 'Wilde Salomé',
 'tt0795461': 'Scary Movie 5',
 'tt0798817': '13',
 'tt0800054': 'The Guardians',
 'tt0800092': 'Ironmen',
 'tt0800320': 'Clash of the Titans',
 'tt0800325': 'The Dirt',
 'tt0800353': 'Nemesis',
 'tt0800369': 'Thor',
 'tt0803061': 'Red Dog',
 'tt0803096': 'Warcraft',
 'tt0804463': "Devil's Knot",
 'tt0804483': 'Folk!',
 'tt0804497': "It's Kind of a Funny Story",
 'tt0804509': 'The Mule',
 'tt0805617': 'Spoon',
 'tt0805647': 'The Witches',
 'tt0808245': 'A Letter to Elia',
 'tt0808447': 'The Last Pogo Jumps Again',
 'tt0808510': 'Tooth Fairy',
 'tt0810772': 'Belle du Seigneur',
 'tt0810815': 'Cross the Line',
 'tt0810819': 'The Danish Girl',
 'tt0810856': 'Eyes of the Mothman',
 'tt0810913': 'Jack and Jill',
 'tt0810922': 'Take Me Home Tonight',
 'tt0811021': 'Plumíferos - Aventuras voladoras',
 'tt0811069': 'Lavoe',
 'tt0811137': 'The Do-Deca-Pentathlon',
 'tt0811613': 'Meridian Lines',
 'tt0813992': 'American Flyer',
 'tt0814255': 'Percy Jackson & the Olympians: The Lightning Thief',
 'tt0815101': 'Ashes',
 'tt0815236': "She's Out of My League",
 'tt0816362': 'Card Subject to Change',
 'tt0816442': 'The Book Thief',
 'tt0816462': 'Conan the Barbarian',
 'tt0816648': 'Shanghai Hotel',
 'tt0816692': 'Interstellar',
 'tt0816711': 'World War Z',
 'tt0817177': 'Flipped',
 'tt0817230': "Valentine's Day",
 'tt0817545': 'The Power of Few',
 'tt0818098': 'Dreamkiller',
 'tt0818172': 'Soupernatural',
 'tt0821486': 'Manhattan Minutiae',
 'tt0822847': 'Priest',
 'tt0825282': 'The Long Falling',
 'tt0825283': 'Maximum Ride',
 'tt0825334': 'Caravaggio and My Mother the Pope',
 'tt0826532': 'Return to Yucca Flats: Desert Man-Beast',
 'tt0826823': 'Magic',
 'tt0828135': 'Wild in the Streets',
 'tt0829150': 'Dracula Untold',
 'tt0829176': 'Gallowwalkers',
 'tt0831280': 'Waking Madison',
 'tt0831387': 'Godzilla',
 'tt0831881': 'Land',
 'tt0835418': 'The Babymakers',
 'tt0835775': 'Electric Slide',
 'tt0835802': 'Krystal',
 'tt0837156': "Pee-wee's Big Holiday",
 'tt0837559': 'Approaching Midnight',
 'tt0837562': 'Hotel Transylvania',
 'tt0837563': 'Pet Sematary',
 'tt0838194': 'Retreat!',
 'tt0839742': 'Bhopal: A Prayer for Rain',
 'tt0840358': 'Everyday Sunshine: The Story of Fishbone',
 'tt0840361': 'The Town',
 'tt0840789': 'Río de oro',
 'tt0841185': 'Whatever Happened to Pete Blaggit?',
 'tt0842926': 'The Kids Are All Right',
 'tt0843839': 'The Fallen Word',
 'tt0844699': "Ivan Mosjoukine ou L'enfant du carnaval",
 'tt0844866': 'Killer by Nature',
 'tt0844915': 'Pox',
 'tt0844993': 'Hoodwinked Too! Hood vs. Evil',
 'tt0846004': 'Gangster Exchange',
 'tt0847180': 'Loot',
 'tt0847215': 'Neowolf',
 'tt0847505': 'Night Traveler',
 'tt0847735': 'Fun in the Army',
 'tt0847825': 'The Speed of Thought',
 'tt0848228': 'The Avengers',
 'tt0848537': 'Epic',
 'tt0848554': 'The Sighting',
 'tt0849437': 'Duel of Legends',
 'tt0850247': 'Amsteroid',
 'tt0850677': 'Jack & Diane',
 'tt0850678': 'Jackson Arms',
 'tt0850709': 'Risen',
 'tt0851471': 'Sir Billi',
 'tt0852441': 'Folie à deux',
 'tt0852939': 'Bloudím',
 'tt0852986': 'Naked Run',
 'tt0853002': 'A Summer Song',
 'tt0853155': 'This Is What Love in Action Looks Like',
 'tt0856796': 'Kolorádó Kid',
 'tt0857190': 'The Sweeney',
 'tt0858411': '2001 Maniacs: Field of Screams',
 'tt0858419': 'Bolden',
 'tt0858422': 'Immortal Island',
 'tt0858500': 'Wide Blue Yonder',
 'tt0859612': 'The Golden Greek: The Harry Agganis Story',
 'tt0859635': 'Super Troopers 2',
 'tt0860907': 'Evangelion: 3.0 You Can (Not) Redo',
 'tt0861747': 'Zenitram',
 'tt0862748': 'Lupin the 3rd',
 'tt0862930': 'Dukun',
 'tt0864835': 'Mr. Peabody & Sherman',
 'tt0865557': 'Letting Go',
 'tt0865561': '6 Month Rule',
 'tt0865911': 'Catharsis',
 'tt0870154': 'Jungle Cruise',
 'tt0870208': 'Touch Wood',
 'tt0871891': 'The Nightclub Days',
 'tt0871893': 'Surprise, Surprise',
 'tt0872230': 'My Soul to Take',
 'tt0873886': 'Red State',
 'tt0874268': 'The Dot Man',
 'tt0874421': 'Beijing Taxi',
 'tt0874426': 'The Secret Philosophy',
 'tt0875612': "Rain Falls from Earth: Surviving Cambodia's Darkest Hour",
 'tt0875613': 'Rift',
 'tt0875702': 'Bury the Hatchet',
 'tt0877604': 'Chûshingura',
 'tt0878654': 'Bulletface',
 'tt0878672': 'First Circle',
 'tt0878814': 'Jewtopia',
 'tt0878835': 'Please Give',
 'tt0879405': "Harm's Way",
 'tt0879859': 'Torn',
 'tt0879870': 'Eat Pray Love',
 'tt0880569': 'Mama I Want to Sing',
 'tt0881320': 'Sanctum',
 'tt0882741': 'AIR: The Musical',
 'tt0882977': 'Snitch',
 'tt0884214': 'Wreckage',
 'tt0884325': 'Drain Baby',
 'tt0884726': "Legends of Oz: Dorothy's Return",
 'tt0884732': 'The Wedding Ringer',
 'tt0887143': 'Hyenas',
 'tt0887161': 'Repo',
 'tt0887266': 'Rollerboy',
 'tt0887751': 'Honor',
 'tt0889573': 'The Switch',
 'tt0891581': 'RxCannabis: A Freedom Tale',
 'tt0892062': 'Hamlet A.D.D.',
 'tt0892077': 'Gun of the Black Sun',
 'tt0892318': 'Letters to Juliet',
 'tt0892769': 'How to Train Your Dragon',
 'tt0892791': 'Shrek Forever After',
 'tt0893310': 'Blur',
 'tt0893412': 'From Prada to Nada',
 'tt0896872': 'The Whistleblower',
 'tt0899145': "Don't Fade Away",
 'tt0899154': 'The Key Man',
 'tt0900387': 'Suite Française',
 'tt0901504': 'Psych:9',
 'tt0902247': 'Acts of Violence',
 'tt0903036': 'Westbrick Murders',
 'tt0903624': 'The Hobbit: An Unexpected Journey',
 'tt0903657': 'Love & Mercy',
 'tt0905372': 'The Thing',
 'tt0906013': 'The Grind',
 'tt0906327': "The Unlikely's",
 'tt0906778': 'Black Butterflies',
 'tt0907305': 'Prey',
 'tt0907731': 'Eager to Die',
 'tt0907852': 'Exposed',
 'tt0910885': "A Merry Friggin' Christmas",
 'tt0910926': "Movin' In",
 'tt0914823': 'House Under Siege',
 'tt0914852': 'Monkeyman935',
 'tt0914863': 'Unthinkable',
 'tt0915463': 'Jackboots on Whitehall',
 'tt0918520': 'Gangster Kittens',
 'tt0918553': 'Periphery',
 'tt0918575': 'Victim',
 'tt0918940': 'The Legend of Tarzan',
 'tt0920459': 'The Happy Housewife',
 'tt0923653': 'The Dead Undead',
 'tt0923954': 'Truth About Kerry',
 'tt0924266': 'Pizza with Bullets',
 'tt0926084': 'Harry Potter and the Deathly Hallows: Part 1',
 'tt0926132': 'Road to Red',
 'tt0926170': "White Men Can't Dance",
 'tt0929618': 'The Penthouse',
 'tt0929742': 'Deep Gold 3D',
 'tt0932667': 'The Man in the Silo',
 'tt0933876': 'June 9',
 'tt0934446': 'Glenn, the Flying Robot',
 'tt0934981': 'The Waiter',
 'tt0935075': 'Rabbit Hole',
 'tt0937225': 'Joe Dick',
 'tt0937353': "The Devil's Flower",
 'tt0938283': 'The Last Airbender',
 'tt0938305': 'Freaky Deaky',
 'tt0938330': 'Silent Hill: Revelation',
 'tt0940656': 'Arthur 3: The War of the Two Worlds',
 'tt0942906': 'White Knuckles',
 'tt0944835': 'Salt',
 'tt0945513': 'Source Code',
 'tt0947798': 'Black Swan',
 'tt0947810': 'Green Zone',
 'tt0948470': 'The Amazing Spider-Man',
 'tt0949872': 'Coffee Sex You',
 'tt0954947': 'The Killer Inside Me',
 'tt0955308': 'Robin Hood',
 'tt0959306': 'Reach Me',
 'tt0959329': 'Nine Dead',
 'tt0960067': 'Heart of Now',
 'tt0960727': 'Let Me Survive',
 'tt0960730': 'Beautiful Darling',
 'tt0960827': 'Private Security Officer: Los Angeles',
 'tt0960864': 'Truth in Numbers? Everything, According to Wikipedia',
 'tt0961036': 'Avenge',
 'tt0961097': 'A Monster in Paris',
 'tt0961725': 'Devour',
 'tt0961755': 'The Trouble with Cali',
 'tt0962764': 'The House of Sun',
 'tt0963177': 'Made in Romania',
 'tt0963292': 'Feast of the Assumption: BTK and the Otero Family Murders',
 'tt0963966': "The Sorcerer's Apprentice",
 'tt0964517': 'The Fighter',
 'tt0964544': "Pushin' Up Daisies",
 'tt0965424': 'Have You Heard from Johannesburg: Hell of a Job',
 'tt0965425': 'Have You Heard from Johannesburg: Road to Resistance',
 'tt0965429': "L'imbroglio nel lenzuolo",
 'tt0968264': 'The Conspirator',
 'tt0969332': 'Little Witch on a Broomstick',
 'tt0969345': 'Strange Frame: Love & Sax',
 'tt0969653': 'White Wall',
 'tt0970179': 'Hugo',
 'tt0970866': 'Little Fockers',
 'tt0970926': 'The Chosen One',
 'tt0970955': 'The Reason',
 'tt0972544': 'Back Roads',
 'tt0972815': 'Have You Heard from Johannesburg: Fair Play',
 'tt0972816': 'Have You Heard from Johannesburg: The Bottom Line',
 'tt0972848': 'Lives and Deaths of the Poets',
 'tt0973809': 'Headhunter: The Assessment Weekend',
 'tt0974015': 'Justice League',
 'tt0974584': 'Black Limousine',
 'tt0975645': 'Hitchcock',
 'tt0975738': 'Sinatra Club',
 'tt0977639': 'Boyle Heights',
 'tt0977643': 'Chooriyan',
 'tt0977855': 'Fair Game',
 'tt0978764': 'Sucker Punch',
 'tt0978812': 'Have You Heard from Johannesburg: Free at Last',
 'tt0979434': 'Lottery Ticket',
 'tt0980970': 'The Chronicles of Narnia: The Voyage of the Dawn Treader',
 'tt0980999': 'Four',
 'tt0981013': 'Heredity',
 'tt0981286': 'Funkytown',
 'tt0983190': 'The Unwanted',
 'tt0983193': 'The Adventures of Tintin',
 'tt0983250': "You're Nobody 'til Somebody Kills You",
 'tt0983946': 'Fantasy Island',
 'tt0984084': 'El Padrino II: Border Intrusion',
 'tt0984113': 'A Dance for Grace',
 'tt0984210': 'Multiple Sarcasms',
 'tt0985694': 'Machete',
 'tt0986361': 'The Magic Crystal',
 'tt0988655': 'A Flat',
 'tt0988858': 'The Gainesville Ripper',
 'tt0989757': 'Dear John',
 'tt0990363': 'Detention',
 'tt0990407': 'The Green Hornet',
 'tt0991173': 'The Significant Other',
 'tt0993842': 'Hanna',
 'tt0993846': 'The Wolf of Wall Street',
 'tt0994917': 'Adventure Scouts',
 'tt0995845': 'The Courier',
 'tt0995867': 'The Unforgiven',
 'tt0995868': 'Pelé: Birth of a Legend',
 'tt0996664': 'The Extendables',
 'tt0996958': 'Legend of the Red Reaper',
 'tt0996976': 'The Slimbones',
 'tt0997035': 'Bibliothèque Pascal',
 'tt0997152': 'The Experiment',
 'tt0997179': 'Looking for the Lost Tango',
 'tt0997232': 'Two Knives',
 'tt0999913': 'Straw Dogs',
 'tt10001116': 'Mistero di un Impiegato',
 'tt10001870': 'Disrupted Land',
 'tt10001940': 'Chalu Dya Tumcha',
 'tt10003008': 'The Rental',
 'tt10003350': 'Lusitanian Ghosts',
 'tt10003792': 'Adalat',
 'tt10003806': 'Jadugar 2',
 'tt10003978': 'Fiddler: A Miracle of Miracles',
 'tt10003990': 'Child of Wisdom',
 'tt10004074': 'Ali the Blind Boxer',
 'tt10004118': 'The Truth: Lost at Sea',
 'tt10004372': 'Soccer in the City',
 'tt10004396': 'When I Became a Butterfly',
 'tt10004574': 'Paradise',
 'tt10004944': 'Aporia',
 'tt10005130': 'Alalá',
 'tt10005184': 'Lysis',
 'tt10005378': 'In Their Own Words, Billy the Kid & The Lincoln County War',
 'tt10005524': 'Invasores',
 'tt10005622': 'Chinese Speaking Vampires',
 'tt10005688': 'Dhuntaaraa',
 'tt10005864': 'Barof 2019',
 'tt10006026': 'The Lost Memories',
 'tt10006056': 'La notte è piccola per noi',
 'tt10006122': 'Debout',
 'tt10006156': 'Krishnam',
 'tt10006160': 'Kala-a-zar',
 'tt10006270': 'Hunting Season',